
[[_introduction]]
= Introduction

Ikonli provides icon packs that can be used in Java applications. Currently Swing and JavaFX UI toolkits are supported.

== Download

Ikonli and all of its icon packs can be downloaded from Bintray
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/ikonli/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/ikonli/_latestVersion"]
and Maven Central
image:https://img.shields.io/maven-central/v/{project-group}/ikonli-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"].

You must select a binary that matches your target UI toolkit, such as

[horizontal]
Swing:: ikonli-swing-{project-version} (JDK 11+) _or_ ikonli-swing-{ikonliJdk8Version} (JDK 8)
JavaFX:: ikonli-javafx-{project-version} (JDK 11+) _or_ ikonli-javafx-{ikonliJdk8Version} (JDK 8)

WARNING: Not all icon packs are available in the JDK8 only version (`{ikonliJdk8Version}`).

Next, select any of the icon packs you want to use. You may select more than one for the same application.

== Breaking Changes

If you are upgrading to `12.0.0` or later be aware of the following changes:

* The module names moved from `org.kordamp.ikonli` to `org.kordamp.ikonli.*`.
* The `icon-hawkconsfilled-pack` and `icon-hawkconsstroke-pack` icon packs were merged into a single `icon-hawkcons-pack` icon pack.
* The `icon-materialdesign-pack` no longer has a single enum named `org.kordamp.ikonli.materialdesign.MaterialDesign` as the
number of icons exceed the limit that enums may have. There are now multiple enums, each one with a letter as prefix, denoting
the initial character of the icon descriptions it holds, for example `org.kordamp.ikonli.materialdesign.MaterialDesignA` holds
all icons that begin with the letter `'a'`.
* The method `getCode()` of `org.kordamp.ikonli.Ikon` now returns `int` instead of `char`. This change is needed to accomodate
icon packs whose icon codes are larger than a single char, such as MaterialDesign.
