
[[_usage]]
= Usage

== Swing

The `ikonli-swing:{project-version}` JAR provides a new Icon class: `{api_link_fonticon_swing}`.
You may use this class with any Swing component that supports an Icon property.

=== Installing

[source,groovy]
[subs="attributes"]
.gradle
----
repositories {
    mavenCentral()
}

dependencies {
    compile '{project-group}:ikonli-swing:{project-version}'
}
----

[source,xml]
[subs="attributes,verbatim"]
.maven
----
<dependencies>
    <dependency>
        <groupId>{project-group}</groupId>
        <artifactId>ikonli-swing</artifactId>
        <version>{project-version}</version>
    </dependency>
</dependencies>
----

== JavaFX

The `ikonli-javafx:{project-version}` JAR provides a new Node class: `{api_link_fonticon_javafx}`.
You may use this class with any JavaFX control that accepts a graphic property. You may also use the icon directly as
it is a subclass of `javafx.scene.text.Text`. The icon class can be used inside an FXML file too.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.control.Button?>
<?import javafx.scene.layout.GridPane?>
<?import org.kordamp.ikonli.javafx.FontIcon?>

<GridPane prefHeight="60.0" prefWidth="200.0"
          xmlns:fx="http://javafx.com/fxml"
          fx:controller="org.example.AppController">
    <Button GridPane.columnIndex="0" GridPane.rowIndex="0"
            mnemonicParsing="false"
            prefWidth="200.0">
        <graphic>
            <FontIcon iconLiteral="di-java" iconSize="64"/>
        </graphic>
    </Button>
</GridPane>
----

.Icon Literal Syntax

The `iconLiteral` property accepts any of these formats

 * icon-code
 * icon-code:icon-size
 * icon-code:icon-size:icon-color

where the following rules apply

icon-code:: An icon code literal such as `di-java`. The prefix (`di-`) indicates the icon pack. For this example, DevIcons needs to be installed.
icon-size:: A number (in pixels) specifying the width of the icon.
icon-color:: A `javafx.scene.paint.Color`, `javafx.scene.paint.LinearGradient`,
or `javafx.scene.paint.RadialGradient` literal.

.Examples
[source]
----
di-java
di-java:32
di-java:64:BLUE
----

.Stylable Properties

`{api_link_fonticon_javafx}` exposes properties that can be styled using CSS. It defines a node class named `ikonli-font-icon`.

[horizontal]
-fx-icon-code:: An icon literal such as `di-java` or `fa-github`.
-fx-icon-size:: The size of the icon, in pixels.
-fx-icon-color:: A JavaFX `Paint` definition, such as a plain color or gradient.

A stackable version is also available, `{api_link_stackedfonticon_javafx}`. This is an specialized version of `javafx.scene.layout.StackPane`
that accepts instances of `{api_link_fonticon_javafx}` as child content. You may use this class with FXML, like it's shown
in the following example

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.layout.GridPane?>
<?import org.kordamp.ikonli.javafx.FontIcon?>
<?import org.kordamp.ikonli.javafx.StackedFontIcon?>

<GridPane prefHeight="60.0" prefWidth="200.0"
          xmlns:fx="http://javafx.com/fxml"
          fx:controller="org.example.AppController">
    <StackedFontIcon GridPane.columnIndex="0" GridPane.rowIndex="0" iconSize="48">
        <FontIcon iconLiteral="fa-circle-thin" iconColor="red"/>
        <FontIcon iconLiteral="fa-camera" StackedFontIcon.iconSize="0.5"/>
    </StackedFontIcon>
</GridPane>
----

.Stylable Properties

`{api_link_stackedfonticon_javafx}` exposes properties that can be styled using CSS. It defines a node class named `stacked-ikonli-font-icon`.

[horizontal]
-fx-icon-size:: The size of the icon, in pixels.
-fx-icon-color:: A JavaFX `Paint` definition, such as a plain color or gradient.

=== Installing

[source,groovy]
[subs="attributes"]
.gradle
----
repositories {
    mavenCentral()
}

dependencies {
    compile '{project-group}:ikonli-javafx:{project-version}'
}
----

[source,xml]
[subs="attributes,verbatim"]
.maven
----
<dependencies>
    <dependency>
        <groupId>{project-group}</groupId>
        <artifactId>ikonli-javafx</artifactId>
        <version>{project-version}</version>
    </dependency>
</dependencies>
----

Next, don't forget to add entries to your module descriptor (`module-info.java`). Here's for example the
minimum settings required for a JavaFX application

[source,java]
.module-info.java
----
module com.acme.demo {
    requires javafx.base;
    requires javafx.graphics;
    requires javafx.controls;
    requires org.kordamp.iconli.core;
    requires org.kordamp.ikonli.javafx;
    // add icon pack modules
    requires org.kordamp.ikonli.fontawesome;
}
----

== Creating a FatJAR

Ikonli's icon packs rely on services files to provide their implementation. You mist make sure that those services files
are properly merged when creating a FatJar or UberJAR. Fortunately there are build plugins that can help with this task.

.Gradle
Configure the `link:https://imperceptiblethoughts.com/shadow/getting-started/[shadow]` plugin and merge service files

[source,groovy]
.build.gradle
----
plugins {
    id 'com.github.johnrengelman.shadow' version '5.2.0'
}

shadowJar {
    mergeServiceFiles()
}
----

.Maven
Configure the `link:https://maven.apache.org/plugins/maven-shade-plugin/[maven-shade-plugin]` and apply the
`org.apache.maven.plugins.shade.resource.ServicesResourceTransformer` transformer.

[source,xml]
[subs="verbatim"]
.pom.xml
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.2.3</version>
    <configuration>
        <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
        </transformers>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----


