= Ikonli
:linkattrs:
:project-owner:   aalmiray
:project-repo:    kordamp
:project-name:    ikonli
:project-group:   org.kordamp.ikonli
:project-version: 11.3.0

image:http://img.shields.io/travis/aalmiray/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/aalmiray/{project-name}"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL3 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

Ikonli provides icon packs that can be used in Java applications. Currently Swing and JavaFX UI toolkits are supported.

== Installing

You can get the latest version of **Ikonli** directly from link:https://bintray.com[Bintray's JCenter] repository or Maven Central.

Refer to the link:http://aalmiray.github.io/ikonli/[guide, window="_blank"] for further information on configuration
and usage.

== Building

You must meet the following requirements:

 * JDK11 as a minimum
 * Gradle 5.0

You may used the included gradle wrapper script if you don't have `gradle` installed.

Adapt these instructions to Windows settings if running on Windows.

=== Installing Gradle

.Manual

 . Download Gradle from http://gradle.org/downloads
 . Unzip the file into a directory without spaces (recommended).
 . Create a GRADLE_HOME environment variable that points to this directory.
 . Adjust your PATH environment variable to include $GRADLE_HOME/bin (%GRADLE_HOME%\bin on Windows).
 . Test your setup by invoking `gradle --version`.

.SDKMAN

 . Follow the instructions found at http://sdkman.io/ to install SDKMAN.
 . You need a POSIX environment if running Windows. We recommend using Babun Shell (http://babun.github.io/)
 . Once SDKMAN is installed invoke `sdk install gradle 4.10`.
 . Test your setup by invoking `gradle --version`.

.Gdub

GDub is a wrapper script that facilitates invoking gradle tasks anywhere within a Gradle project. It's smart enough
to use the gradle wrapper if available or your global gradle command. This is an optional download.

 . Follow the instructions found at https://github.com/dougborg/gdub to install gdub

=== Next Steps

Make a full build issuing `gradle build`.

Run the sampler JavaFX application by invoking the following commands

[source]
----
$ cd subprojects/sampler-javafx
$ ../gradlew run
----

Run the sampler Swing application by invoking the following commands
[source]
----
$ cd subprojects/sampler-swing
$ ../gradlew run
----
