= Ikonli
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    ikonli
:project-group:   org.kordamp.ikonli
:project-version: 12.3.0

image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

---

Ikonli provides icon packs that can be used in Java applications. Currently Swing and JavaFX UI toolkits are supported.

== Installing

You can get the latest version of **Ikonli** directly from link:https://search.maven.org/#search|ga|1|{project-group}[Maven Central].

Refer to the link:http://{project-owner}.github.io/ikonli/[guide, window="_blank"] for further information on configuration
and usage.

== Building

You must meet the following requirements:

 * JDK11 as a minimum
 * Gradle 6.0

You may use the included gradle wrapper script if you don't have `gradle` installed.

Adapt these instructions to Windows settings if running on Windows.

=== Installing Gradle

.Manual

 . Download Gradle from http://gradle.org/downloads
 . Unzip the file into a directory without spaces (recommended).
 . Create a GRADLE_HOME environment variable that points to this directory.
 . Adjust your PATH environment variable to include $GRADLE_HOME/bin (%GRADLE_HOME%\bin on Windows).
 . Test your setup by invoking `gradle --version`.

.SDKMAN

 . Follow the instructions found at http://sdkman.io/ to install SDKMAN.
 . You need a POSIX environment if running Windows. We recommend using Babun Shell (http://babun.github.io/)
 . Once SDKMAN is installed invoke `sdk install gradle 6.3`.
 . Test your setup by invoking `gradle --version`.

.Gum

Gum is a wrapper script that facilitates invoking gradle tasks anywhere within a Gradle project. It's smart enough
to use the gradle wrapper if available or your global gradle command. This is an optional download.

 . Follow the instructions found at https://github.com/kordamp/gm to install gum

=== Next Steps

Make a full build issuing `gm build`.

Run the sampler JavaFX application by invoking the following command
[source]
----
$ gm :sampler-javafx:run
----

Run the sampler Swing application by invoking the following command
[source]
----
$ gm :sampler-swing:run
----

Run the Ikonli Browser application  by invoking the following command
[source]
----
$ gm :ikonli-browser:run
----

=== Publishing your own SNAPSHOT

You can publish a local snapshot release by issuing this command

[source]
----
$ gm install
----

If you don't Gum installed then issue this command

[source]
----
$ ./gradlew publishToMavenLocal
----

