/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2015-2020 Andres Almiray
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kordamp.ikonli.materialdesign;

import org.kordamp.ikonli.Ikon;

/**
 * @author Andres Almiray
 */
public enum MaterialDesignD implements Ikon {
    DANCE_BALLROOM("mdid-dance-ballroom", "F15FB"),
    DANCE_POLE("mdid-dance-pole", "F1578"),
    DATA_MATRIX("mdid-data-matrix", "F153C"),
    DATA_MATRIX_EDIT("mdid-data-matrix-edit", "F153D"),
    DATA_MATRIX_MINUS("mdid-data-matrix-minus", "F153E"),
    DATA_MATRIX_PLUS("mdid-data-matrix-plus", "F153F"),
    DATA_MATRIX_REMOVE("mdid-data-matrix-remove", "F1540"),
    DATA_MATRIX_SCAN("mdid-data-matrix-scan", "F1541"),
    DATABASE("mdid-database", "F01BC"),
    DATABASE_ALERT("mdid-database-alert", "F163A"),
    DATABASE_ALERT_OUTLINE("mdid-database-alert-outline", "F1624"),
    DATABASE_ARROW_DOWN("mdid-database-arrow-down", "F163B"),
    DATABASE_ARROW_DOWN_OUTLINE("mdid-database-arrow-down-outline", "F1625"),
    DATABASE_ARROW_LEFT("mdid-database-arrow-left", "F163C"),
    DATABASE_ARROW_LEFT_OUTLINE("mdid-database-arrow-left-outline", "F1626"),
    DATABASE_ARROW_RIGHT("mdid-database-arrow-right", "F163D"),
    DATABASE_ARROW_RIGHT_OUTLINE("mdid-database-arrow-right-outline", "F1627"),
    DATABASE_ARROW_UP("mdid-database-arrow-up", "F163E"),
    DATABASE_ARROW_UP_OUTLINE("mdid-database-arrow-up-outline", "F1628"),
    DATABASE_CHECK("mdid-database-check", "F0AA9"),
    DATABASE_CHECK_OUTLINE("mdid-database-check-outline", "F1629"),
    DATABASE_CLOCK("mdid-database-clock", "F163F"),
    DATABASE_CLOCK_OUTLINE("mdid-database-clock-outline", "F162A"),
    DATABASE_COG("mdid-database-cog", "F164B"),
    DATABASE_COG_OUTLINE("mdid-database-cog-outline", "F164C"),
    DATABASE_EDIT("mdid-database-edit", "F0B86"),
    DATABASE_EDIT_OUTLINE("mdid-database-edit-outline", "F162B"),
    DATABASE_EXPORT("mdid-database-export", "F095E"),
    DATABASE_EXPORT_OUTLINE("mdid-database-export-outline", "F162C"),
    DATABASE_IMPORT("mdid-database-import", "F095D"),
    DATABASE_IMPORT_OUTLINE("mdid-database-import-outline", "F162D"),
    DATABASE_LOCK("mdid-database-lock", "F0AAA"),
    DATABASE_LOCK_OUTLINE("mdid-database-lock-outline", "F162E"),
    DATABASE_MARKER("mdid-database-marker", "F12F6"),
    DATABASE_MARKER_OUTLINE("mdid-database-marker-outline", "F162F"),
    DATABASE_MINUS("mdid-database-minus", "F01BB"),
    DATABASE_MINUS_OUTLINE("mdid-database-minus-outline", "F1630"),
    DATABASE_OFF("mdid-database-off", "F1640"),
    DATABASE_OFF_OUTLINE("mdid-database-off-outline", "F1631"),
    DATABASE_OUTLINE("mdid-database-outline", "F1632"),
    DATABASE_PLUS("mdid-database-plus", "F01BA"),
    DATABASE_PLUS_OUTLINE("mdid-database-plus-outline", "F1633"),
    DATABASE_REFRESH("mdid-database-refresh", "F05C2"),
    DATABASE_REFRESH_OUTLINE("mdid-database-refresh-outline", "F1634"),
    DATABASE_REMOVE("mdid-database-remove", "F0D00"),
    DATABASE_REMOVE_OUTLINE("mdid-database-remove-outline", "F1635"),
    DATABASE_SEARCH("mdid-database-search", "F0866"),
    DATABASE_SEARCH_OUTLINE("mdid-database-search-outline", "F1636"),
    DATABASE_SETTINGS("mdid-database-settings", "F0D01"),
    DATABASE_SETTINGS_OUTLINE("mdid-database-settings-outline", "F1637"),
    DATABASE_SYNC("mdid-database-sync", "F0CFF"),
    DATABASE_SYNC_OUTLINE("mdid-database-sync-outline", "F1638"),
    DEATH_STAR("mdid-death-star", "F08D8"),
    DEATH_STAR_VARIANT("mdid-death-star-variant", "F08D9"),
    DEATHLY_HALLOWS("mdid-deathly-hallows", "F0B87"),
    DEBIAN("mdid-debian", "F08DA"),
    DEBUG_STEP_INTO("mdid-debug-step-into", "F01B9"),
    DEBUG_STEP_OUT("mdid-debug-step-out", "F01B8"),
    DEBUG_STEP_OVER("mdid-debug-step-over", "F01B7"),
    DECAGRAM("mdid-decagram", "F076C"),
    DECAGRAM_OUTLINE("mdid-decagram-outline", "F076D"),
    DECIMAL("mdid-decimal", "F10A1"),
    DECIMAL_COMMA("mdid-decimal-comma", "F10A2"),
    DECIMAL_COMMA_DECREASE("mdid-decimal-comma-decrease", "F10A3"),
    DECIMAL_COMMA_INCREASE("mdid-decimal-comma-increase", "F10A4"),
    DECIMAL_DECREASE("mdid-decimal-decrease", "F01B6"),
    DECIMAL_INCREASE("mdid-decimal-increase", "F01B5"),
    DELETE("mdid-delete", "F01B4"),
    DELETE_ALERT("mdid-delete-alert", "F10A5"),
    DELETE_ALERT_OUTLINE("mdid-delete-alert-outline", "F10A6"),
    DELETE_CIRCLE("mdid-delete-circle", "F0683"),
    DELETE_CIRCLE_OUTLINE("mdid-delete-circle-outline", "F0B88"),
    DELETE_CLOCK("mdid-delete-clock", "F1556"),
    DELETE_CLOCK_OUTLINE("mdid-delete-clock-outline", "F1557"),
    DELETE_EMPTY("mdid-delete-empty", "F06CC"),
    DELETE_EMPTY_OUTLINE("mdid-delete-empty-outline", "F0E9D"),
    DELETE_FOREVER("mdid-delete-forever", "F05E8"),
    DELETE_FOREVER_OUTLINE("mdid-delete-forever-outline", "F0B89"),
    DELETE_OFF("mdid-delete-off", "F10A7"),
    DELETE_OFF_OUTLINE("mdid-delete-off-outline", "F10A8"),
    DELETE_OUTLINE("mdid-delete-outline", "F09E7"),
    DELETE_RESTORE("mdid-delete-restore", "F0819"),
    DELETE_SWEEP("mdid-delete-sweep", "F05E9"),
    DELETE_SWEEP_OUTLINE("mdid-delete-sweep-outline", "F0C62"),
    DELETE_VARIANT("mdid-delete-variant", "F01B3"),
    DELTA("mdid-delta", "F01C2"),
    DESK("mdid-desk", "F1239"),
    DESK_LAMP("mdid-desk-lamp", "F095F"),
    DESKPHONE("mdid-deskphone", "F01C3"),
    DESKTOP_CLASSIC("mdid-desktop-classic", "F07C0"),
    DESKTOP_MAC("mdid-desktop-mac", "F01C4"),
    DESKTOP_MAC_DASHBOARD("mdid-desktop-mac-dashboard", "F09E8"),
    DESKTOP_TOWER("mdid-desktop-tower", "F01C5"),
    DESKTOP_TOWER_MONITOR("mdid-desktop-tower-monitor", "F0AAB"),
    DETAILS("mdid-details", "F01C6"),
    DEV_TO("mdid-dev-to", "F0D6E"),
    DEVELOPER_BOARD("mdid-developer-board", "F0697"),
    DEVIANTART("mdid-deviantart", "F01C7"),
    DEVICES("mdid-devices", "F0FB0"),
    DIABETES("mdid-diabetes", "F1126"),
    DIALPAD("mdid-dialpad", "F061C"),
    DIAMETER("mdid-diameter", "F0C63"),
    DIAMETER_OUTLINE("mdid-diameter-outline", "F0C64"),
    DIAMETER_VARIANT("mdid-diameter-variant", "F0C65"),
    DIAMOND("mdid-diamond", "F0B8A"),
    DIAMOND_OUTLINE("mdid-diamond-outline", "F0B8B"),
    DIAMOND_STONE("mdid-diamond-stone", "F01C8"),
    DICE_1("mdid-dice-1", "F01CA"),
    DICE_1_OUTLINE("mdid-dice-1-outline", "F114A"),
    DICE_2("mdid-dice-2", "F01CB"),
    DICE_2_OUTLINE("mdid-dice-2-outline", "F114B"),
    DICE_3("mdid-dice-3", "F01CC"),
    DICE_3_OUTLINE("mdid-dice-3-outline", "F114C"),
    DICE_4("mdid-dice-4", "F01CD"),
    DICE_4_OUTLINE("mdid-dice-4-outline", "F114D"),
    DICE_5("mdid-dice-5", "F01CE"),
    DICE_5_OUTLINE("mdid-dice-5-outline", "F114E"),
    DICE_6("mdid-dice-6", "F01CF"),
    DICE_6_OUTLINE("mdid-dice-6-outline", "F114F"),
    DICE_D10("mdid-dice-d10", "F1153"),
    DICE_D10_OUTLINE("mdid-dice-d10-outline", "F076F"),
    DICE_D12("mdid-dice-d12", "F1154"),
    DICE_D12_OUTLINE("mdid-dice-d12-outline", "F0867"),
    DICE_D20("mdid-dice-d20", "F1155"),
    DICE_D20_OUTLINE("mdid-dice-d20-outline", "F05EA"),
    DICE_D4("mdid-dice-d4", "F1150"),
    DICE_D4_OUTLINE("mdid-dice-d4-outline", "F05EB"),
    DICE_D6("mdid-dice-d6", "F1151"),
    DICE_D6_OUTLINE("mdid-dice-d6-outline", "F05ED"),
    DICE_D8("mdid-dice-d8", "F1152"),
    DICE_D8_OUTLINE("mdid-dice-d8-outline", "F05EC"),
    DICE_MULTIPLE("mdid-dice-multiple", "F076E"),
    DICE_MULTIPLE_OUTLINE("mdid-dice-multiple-outline", "F1156"),
    DIGITAL_OCEAN("mdid-digital-ocean", "F1237"),
    DIP_SWITCH("mdid-dip-switch", "F07C1"),
    DIRECTIONS("mdid-directions", "F01D0"),
    DIRECTIONS_FORK("mdid-directions-fork", "F0641"),
    DISC("mdid-disc", "F05EE"),
    DISC_ALERT("mdid-disc-alert", "F01D1"),
    DISC_PLAYER("mdid-disc-player", "F0960"),
    DISCORD("mdid-discord", "F066F"),
    DISHWASHER("mdid-dishwasher", "F0AAC"),
    DISHWASHER_ALERT("mdid-dishwasher-alert", "F11B8"),
    DISHWASHER_OFF("mdid-dishwasher-off", "F11B9"),
    DISQUS("mdid-disqus", "F01D2"),
    DISTRIBUTE_HORIZONTAL_CENTER("mdid-distribute-horizontal-center", "F11C9"),
    DISTRIBUTE_HORIZONTAL_LEFT("mdid-distribute-horizontal-left", "F11C8"),
    DISTRIBUTE_HORIZONTAL_RIGHT("mdid-distribute-horizontal-right", "F11CA"),
    DISTRIBUTE_VERTICAL_BOTTOM("mdid-distribute-vertical-bottom", "F11CB"),
    DISTRIBUTE_VERTICAL_CENTER("mdid-distribute-vertical-center", "F11CC"),
    DISTRIBUTE_VERTICAL_TOP("mdid-distribute-vertical-top", "F11CD"),
    DIVING_FLIPPERS("mdid-diving-flippers", "F0DBF"),
    DIVING_HELMET("mdid-diving-helmet", "F0DC0"),
    DIVING_SCUBA("mdid-diving-scuba", "F0DC1"),
    DIVING_SCUBA_FLAG("mdid-diving-scuba-flag", "F0DC2"),
    DIVING_SCUBA_TANK("mdid-diving-scuba-tank", "F0DC3"),
    DIVING_SCUBA_TANK_MULTIPLE("mdid-diving-scuba-tank-multiple", "F0DC4"),
    DIVING_SNORKEL("mdid-diving-snorkel", "F0DC5"),
    DIVISION("mdid-division", "F01D4"),
    DIVISION_BOX("mdid-division-box", "F01D5"),
    DLNA("mdid-dlna", "F0A41"),
    DNA("mdid-dna", "F0684"),
    DNS("mdid-dns", "F01D6"),
    DNS_OUTLINE("mdid-dns-outline", "F0B8C"),
    DO_NOT_DISTURB("mdid-do-not-disturb", "F0698"),
    DO_NOT_DISTURB_OFF("mdid-do-not-disturb-off", "F0699"),
    DOCK_BOTTOM("mdid-dock-bottom", "F10A9"),
    DOCK_LEFT("mdid-dock-left", "F10AA"),
    DOCK_RIGHT("mdid-dock-right", "F10AB"),
    DOCK_TOP("mdid-dock-top", "F1513"),
    DOCK_WINDOW("mdid-dock-window", "F10AC"),
    DOCKER("mdid-docker", "F0868"),
    DOCTOR("mdid-doctor", "F0A42"),
    DOG("mdid-dog", "F0A43"),
    DOG_SERVICE("mdid-dog-service", "F0AAD"),
    DOG_SIDE("mdid-dog-side", "F0A44"),
    DOLBY("mdid-dolby", "F06B3"),
    DOLLY("mdid-dolly", "F0E9E"),
    DOMAIN("mdid-domain", "F01D7"),
    DOMAIN_OFF("mdid-domain-off", "F0D6F"),
    DOMAIN_PLUS("mdid-domain-plus", "F10AD"),
    DOMAIN_REMOVE("mdid-domain-remove", "F10AE"),
    DOME_LIGHT("mdid-dome-light", "F141E"),
    DOMINO_MASK("mdid-domino-mask", "F1023"),
    DONKEY("mdid-donkey", "F07C2"),
    DOOR("mdid-door", "F081A"),
    DOOR_CLOSED("mdid-door-closed", "F081B"),
    DOOR_CLOSED_LOCK("mdid-door-closed-lock", "F10AF"),
    DOOR_OPEN("mdid-door-open", "F081C"),
    DOORBELL("mdid-doorbell", "F12E6"),
    DOORBELL_VIDEO("mdid-doorbell-video", "F0869"),
    DOT_NET("mdid-dot-net", "F0AAE"),
    DOTS_GRID("mdid-dots-grid", "F15FC"),
    DOTS_HEXAGON("mdid-dots-hexagon", "F15FF"),
    DOTS_HORIZONTAL("mdid-dots-horizontal", "F01D8"),
    DOTS_HORIZONTAL_CIRCLE("mdid-dots-horizontal-circle", "F07C3"),
    DOTS_HORIZONTAL_CIRCLE_OUTLINE("mdid-dots-horizontal-circle-outline", "F0B8D"),
    DOTS_SQUARE("mdid-dots-square", "F15FD"),
    DOTS_TRIANGLE("mdid-dots-triangle", "F15FE"),
    DOTS_VERTICAL("mdid-dots-vertical", "F01D9"),
    DOTS_VERTICAL_CIRCLE("mdid-dots-vertical-circle", "F07C4"),
    DOTS_VERTICAL_CIRCLE_OUTLINE("mdid-dots-vertical-circle-outline", "F0B8E"),
    DOUBAN("mdid-douban", "F069A"),
    DOWNLOAD("mdid-download", "F01DA"),
    DOWNLOAD_BOX("mdid-download-box", "F1462"),
    DOWNLOAD_BOX_OUTLINE("mdid-download-box-outline", "F1463"),
    DOWNLOAD_CIRCLE("mdid-download-circle", "F1464"),
    DOWNLOAD_CIRCLE_OUTLINE("mdid-download-circle-outline", "F1465"),
    DOWNLOAD_LOCK("mdid-download-lock", "F1320"),
    DOWNLOAD_LOCK_OUTLINE("mdid-download-lock-outline", "F1321"),
    DOWNLOAD_MULTIPLE("mdid-download-multiple", "F09E9"),
    DOWNLOAD_NETWORK("mdid-download-network", "F06F4"),
    DOWNLOAD_NETWORK_OUTLINE("mdid-download-network-outline", "F0C66"),
    DOWNLOAD_OFF("mdid-download-off", "F10B0"),
    DOWNLOAD_OFF_OUTLINE("mdid-download-off-outline", "F10B1"),
    DOWNLOAD_OUTLINE("mdid-download-outline", "F0B8F"),
    DRAG("mdid-drag", "F01DB"),
    DRAG_HORIZONTAL("mdid-drag-horizontal", "F01DC"),
    DRAG_HORIZONTAL_VARIANT("mdid-drag-horizontal-variant", "F12F0"),
    DRAG_VARIANT("mdid-drag-variant", "F0B90"),
    DRAG_VERTICAL("mdid-drag-vertical", "F01DD"),
    DRAG_VERTICAL_VARIANT("mdid-drag-vertical-variant", "F12F1"),
    DRAMA_MASKS("mdid-drama-masks", "F0D02"),
    DRAW("mdid-draw", "F0F49"),
    DRAWING("mdid-drawing", "F01DE"),
    DRAWING_BOX("mdid-drawing-box", "F01DF"),
    DRESSER("mdid-dresser", "F0F4A"),
    DRESSER_OUTLINE("mdid-dresser-outline", "F0F4B"),
    DRONE("mdid-drone", "F01E2"),
    DROPBOX("mdid-dropbox", "F01E3"),
    DRUPAL("mdid-drupal", "F01E4"),
    DUCK("mdid-duck", "F01E5"),
    DUMBBELL("mdid-dumbbell", "F01E6"),
    DUMP_TRUCK("mdid-dump-truck", "F0C67");

    public static MaterialDesignD findByDescription(String description) {
        for (MaterialDesignD font : values()) {
            if (font.getDescription().equals(description)) {
                return font;
            }
        }
        throw new IllegalArgumentException("Icon description '" + description + "' is invalid!");
    }

    private String description;
    private int code;

    MaterialDesignD(String description, String code) {
        this.description = description;
        this.code = Integer.parseInt(code, 16);
    }

    @Override
    public String getDescription() {
        return description;
    }

    @Override
    public int getCode() {
        return code;
    }
}
