/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2015-2020 Andres Almiray
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kordamp.ikonli.materialdesign;

import org.kordamp.ikonli.Ikon;

/**
 * @author Andres Almiray
 */
public enum MaterialDesignT implements Ikon {
    TAB("mdit-tab", "F04E9"),
    TAB_MINUS("mdit-tab-minus", "F0B4B"),
    TAB_PLUS("mdit-tab-plus", "F075C"),
    TAB_REMOVE("mdit-tab-remove", "F0B4C"),
    TAB_UNSELECTED("mdit-tab-unselected", "F04EA"),
    TABLE("mdit-table", "F04EB"),
    TABLE_ACCOUNT("mdit-table-account", "F13B9"),
    TABLE_ALERT("mdit-table-alert", "F13BA"),
    TABLE_ARROW_DOWN("mdit-table-arrow-down", "F13BB"),
    TABLE_ARROW_LEFT("mdit-table-arrow-left", "F13BC"),
    TABLE_ARROW_RIGHT("mdit-table-arrow-right", "F13BD"),
    TABLE_ARROW_UP("mdit-table-arrow-up", "F13BE"),
    TABLE_BORDER("mdit-table-border", "F0A18"),
    TABLE_CANCEL("mdit-table-cancel", "F13BF"),
    TABLE_CHAIR("mdit-table-chair", "F1061"),
    TABLE_CHECK("mdit-table-check", "F13C0"),
    TABLE_CLOCK("mdit-table-clock", "F13C1"),
    TABLE_COG("mdit-table-cog", "F13C2"),
    TABLE_COLUMN("mdit-table-column", "F0835"),
    TABLE_COLUMN_PLUS_AFTER("mdit-table-column-plus-after", "F04EC"),
    TABLE_COLUMN_PLUS_BEFORE("mdit-table-column-plus-before", "F04ED"),
    TABLE_COLUMN_REMOVE("mdit-table-column-remove", "F04EE"),
    TABLE_COLUMN_WIDTH("mdit-table-column-width", "F04EF"),
    TABLE_EDIT("mdit-table-edit", "F04F0"),
    TABLE_EYE("mdit-table-eye", "F1094"),
    TABLE_EYE_OFF("mdit-table-eye-off", "F13C3"),
    TABLE_FURNITURE("mdit-table-furniture", "F05BC"),
    TABLE_HEADERS_EYE("mdit-table-headers-eye", "F121D"),
    TABLE_HEADERS_EYE_OFF("mdit-table-headers-eye-off", "F121E"),
    TABLE_HEART("mdit-table-heart", "F13C4"),
    TABLE_KEY("mdit-table-key", "F13C5"),
    TABLE_LARGE("mdit-table-large", "F04F1"),
    TABLE_LARGE_PLUS("mdit-table-large-plus", "F0F87"),
    TABLE_LARGE_REMOVE("mdit-table-large-remove", "F0F88"),
    TABLE_LOCK("mdit-table-lock", "F13C6"),
    TABLE_MERGE_CELLS("mdit-table-merge-cells", "F09A6"),
    TABLE_MINUS("mdit-table-minus", "F13C7"),
    TABLE_MULTIPLE("mdit-table-multiple", "F13C8"),
    TABLE_NETWORK("mdit-table-network", "F13C9"),
    TABLE_OF_CONTENTS("mdit-table-of-contents", "F0836"),
    TABLE_OFF("mdit-table-off", "F13CA"),
    TABLE_PLUS("mdit-table-plus", "F0A75"),
    TABLE_REFRESH("mdit-table-refresh", "F13A0"),
    TABLE_REMOVE("mdit-table-remove", "F0A76"),
    TABLE_ROW("mdit-table-row", "F0837"),
    TABLE_ROW_HEIGHT("mdit-table-row-height", "F04F2"),
    TABLE_ROW_PLUS_AFTER("mdit-table-row-plus-after", "F04F3"),
    TABLE_ROW_PLUS_BEFORE("mdit-table-row-plus-before", "F04F4"),
    TABLE_ROW_REMOVE("mdit-table-row-remove", "F04F5"),
    TABLE_SEARCH("mdit-table-search", "F090F"),
    TABLE_SETTINGS("mdit-table-settings", "F0838"),
    TABLE_SPLIT_CELL("mdit-table-split-cell", "F142A"),
    TABLE_STAR("mdit-table-star", "F13CB"),
    TABLE_SYNC("mdit-table-sync", "F13A1"),
    TABLE_TENNIS("mdit-table-tennis", "F0E68"),
    TABLET("mdit-tablet", "F04F6"),
    TABLET_ANDROID("mdit-tablet-android", "F04F7"),
    TABLET_CELLPHONE("mdit-tablet-cellphone", "F09A7"),
    TABLET_DASHBOARD("mdit-tablet-dashboard", "F0ECE"),
    TABLET_IPAD("mdit-tablet-ipad", "F04F8"),
    TACO("mdit-taco", "F0762"),
    TAG("mdit-tag", "F04F9"),
    TAG_FACES("mdit-tag-faces", "F04FA"),
    TAG_HEART("mdit-tag-heart", "F068B"),
    TAG_HEART_OUTLINE("mdit-tag-heart-outline", "F0BCF"),
    TAG_MINUS("mdit-tag-minus", "F0910"),
    TAG_MINUS_OUTLINE("mdit-tag-minus-outline", "F121F"),
    TAG_MULTIPLE("mdit-tag-multiple", "F04FB"),
    TAG_MULTIPLE_OUTLINE("mdit-tag-multiple-outline", "F12F7"),
    TAG_OFF("mdit-tag-off", "F1220"),
    TAG_OFF_OUTLINE("mdit-tag-off-outline", "F1221"),
    TAG_OUTLINE("mdit-tag-outline", "F04FC"),
    TAG_PLUS("mdit-tag-plus", "F0722"),
    TAG_PLUS_OUTLINE("mdit-tag-plus-outline", "F1222"),
    TAG_REMOVE("mdit-tag-remove", "F0723"),
    TAG_REMOVE_OUTLINE("mdit-tag-remove-outline", "F1223"),
    TAG_TEXT("mdit-tag-text", "F1224"),
    TAG_TEXT_OUTLINE("mdit-tag-text-outline", "F04FD"),
    TAILWIND("mdit-tailwind", "F13FF"),
    TANK("mdit-tank", "F0D3A"),
    TANKER_TRUCK("mdit-tanker-truck", "F0FE5"),
    TAPE_DRIVE("mdit-tape-drive", "F16DF"),
    TAPE_MEASURE("mdit-tape-measure", "F0B4D"),
    TARGET("mdit-target", "F04FE"),
    TARGET_ACCOUNT("mdit-target-account", "F0BD0"),
    TARGET_VARIANT("mdit-target-variant", "F0A77"),
    TAXI("mdit-taxi", "F04FF"),
    TEA("mdit-tea", "F0D9E"),
    TEA_OUTLINE("mdit-tea-outline", "F0D9F"),
    TEACH("mdit-teach", "F0890"),
    TEAMVIEWER("mdit-teamviewer", "F0500"),
    TELEGRAM("mdit-telegram", "F0501"),
    TELESCOPE("mdit-telescope", "F0B4E"),
    TELEVISION("mdit-television", "F0502"),
    TELEVISION_AMBIENT_LIGHT("mdit-television-ambient-light", "F1356"),
    TELEVISION_BOX("mdit-television-box", "F0839"),
    TELEVISION_CLASSIC("mdit-television-classic", "F07F4"),
    TELEVISION_CLASSIC_OFF("mdit-television-classic-off", "F083A"),
    TELEVISION_CLEAN("mdit-television-clean", "F1110"),
    TELEVISION_GUIDE("mdit-television-guide", "F0503"),
    TELEVISION_OFF("mdit-television-off", "F083B"),
    TELEVISION_PAUSE("mdit-television-pause", "F0F89"),
    TELEVISION_PLAY("mdit-television-play", "F0ECF"),
    TELEVISION_STOP("mdit-television-stop", "F0F8A"),
    TEMPERATURE_CELSIUS("mdit-temperature-celsius", "F0504"),
    TEMPERATURE_FAHRENHEIT("mdit-temperature-fahrenheit", "F0505"),
    TEMPERATURE_KELVIN("mdit-temperature-kelvin", "F0506"),
    TENNIS("mdit-tennis", "F0DA0"),
    TENNIS_BALL("mdit-tennis-ball", "F0507"),
    TENT("mdit-tent", "F0508"),
    TERRAFORM("mdit-terraform", "F1062"),
    TERRAIN("mdit-terrain", "F0509"),
    TEST_TUBE("mdit-test-tube", "F0668"),
    TEST_TUBE_EMPTY("mdit-test-tube-empty", "F0911"),
    TEST_TUBE_OFF("mdit-test-tube-off", "F0912"),
    TEXT("mdit-text", "F09A8"),
    TEXT_ACCOUNT("mdit-text-account", "F1570"),
    TEXT_BOX("mdit-text-box", "F021A"),
    TEXT_BOX_CHECK("mdit-text-box-check", "F0EA6"),
    TEXT_BOX_CHECK_OUTLINE("mdit-text-box-check-outline", "F0EA7"),
    TEXT_BOX_MINUS("mdit-text-box-minus", "F0EA8"),
    TEXT_BOX_MINUS_OUTLINE("mdit-text-box-minus-outline", "F0EA9"),
    TEXT_BOX_MULTIPLE("mdit-text-box-multiple", "F0AB7"),
    TEXT_BOX_MULTIPLE_OUTLINE("mdit-text-box-multiple-outline", "F0AB8"),
    TEXT_BOX_OUTLINE("mdit-text-box-outline", "F09ED"),
    TEXT_BOX_PLUS("mdit-text-box-plus", "F0EAA"),
    TEXT_BOX_PLUS_OUTLINE("mdit-text-box-plus-outline", "F0EAB"),
    TEXT_BOX_REMOVE("mdit-text-box-remove", "F0EAC"),
    TEXT_BOX_REMOVE_OUTLINE("mdit-text-box-remove-outline", "F0EAD"),
    TEXT_BOX_SEARCH("mdit-text-box-search", "F0EAE"),
    TEXT_BOX_SEARCH_OUTLINE("mdit-text-box-search-outline", "F0EAF"),
    TEXT_RECOGNITION("mdit-text-recognition", "F113D"),
    TEXT_SEARCH("mdit-text-search", "F13B8"),
    TEXT_SHADOW("mdit-text-shadow", "F0669"),
    TEXT_SHORT("mdit-text-short", "F09A9"),
    TEXT_SUBJECT("mdit-text-subject", "F09AA"),
    TEXT_TO_SPEECH("mdit-text-to-speech", "F050A"),
    TEXT_TO_SPEECH_OFF("mdit-text-to-speech-off", "F050B"),
    TEXTURE("mdit-texture", "F050C"),
    TEXTURE_BOX("mdit-texture-box", "F0FE6"),
    THEATER("mdit-theater", "F050D"),
    THEME_LIGHT_DARK("mdit-theme-light-dark", "F050E"),
    THERMOMETER("mdit-thermometer", "F050F"),
    THERMOMETER_ALERT("mdit-thermometer-alert", "F0E01"),
    THERMOMETER_CHEVRON_DOWN("mdit-thermometer-chevron-down", "F0E02"),
    THERMOMETER_CHEVRON_UP("mdit-thermometer-chevron-up", "F0E03"),
    THERMOMETER_HIGH("mdit-thermometer-high", "F10C2"),
    THERMOMETER_LINES("mdit-thermometer-lines", "F0510"),
    THERMOMETER_LOW("mdit-thermometer-low", "F10C3"),
    THERMOMETER_MINUS("mdit-thermometer-minus", "F0E04"),
    THERMOMETER_OFF("mdit-thermometer-off", "F1531"),
    THERMOMETER_PLUS("mdit-thermometer-plus", "F0E05"),
    THERMOSTAT("mdit-thermostat", "F0393"),
    THERMOSTAT_BOX("mdit-thermostat-box", "F0891"),
    THOUGHT_BUBBLE("mdit-thought-bubble", "F07F6"),
    THOUGHT_BUBBLE_OUTLINE("mdit-thought-bubble-outline", "F07F7"),
    THUMB_DOWN("mdit-thumb-down", "F0511"),
    THUMB_DOWN_OUTLINE("mdit-thumb-down-outline", "F0512"),
    THUMB_UP("mdit-thumb-up", "F0513"),
    THUMB_UP_OUTLINE("mdit-thumb-up-outline", "F0514"),
    THUMBS_UP_DOWN("mdit-thumbs-up-down", "F0515"),
    TICKET("mdit-ticket", "F0516"),
    TICKET_ACCOUNT("mdit-ticket-account", "F0517"),
    TICKET_CONFIRMATION("mdit-ticket-confirmation", "F0518"),
    TICKET_CONFIRMATION_OUTLINE("mdit-ticket-confirmation-outline", "F13AA"),
    TICKET_OUTLINE("mdit-ticket-outline", "F0913"),
    TICKET_PERCENT("mdit-ticket-percent", "F0724"),
    TICKET_PERCENT_OUTLINE("mdit-ticket-percent-outline", "F142B"),
    TIE("mdit-tie", "F0519"),
    TILDE("mdit-tilde", "F0725"),
    TIMELAPSE("mdit-timelapse", "F051A"),
    TIMELINE("mdit-timeline", "F0BD1"),
    TIMELINE_ALERT("mdit-timeline-alert", "F0F95"),
    TIMELINE_ALERT_OUTLINE("mdit-timeline-alert-outline", "F0F98"),
    TIMELINE_CHECK("mdit-timeline-check", "F1532"),
    TIMELINE_CHECK_OUTLINE("mdit-timeline-check-outline", "F1533"),
    TIMELINE_CLOCK("mdit-timeline-clock", "F11FB"),
    TIMELINE_CLOCK_OUTLINE("mdit-timeline-clock-outline", "F11FC"),
    TIMELINE_HELP("mdit-timeline-help", "F0F99"),
    TIMELINE_HELP_OUTLINE("mdit-timeline-help-outline", "F0F9A"),
    TIMELINE_MINUS("mdit-timeline-minus", "F1534"),
    TIMELINE_MINUS_OUTLINE("mdit-timeline-minus-outline", "F1535"),
    TIMELINE_OUTLINE("mdit-timeline-outline", "F0BD2"),
    TIMELINE_PLUS("mdit-timeline-plus", "F0F96"),
    TIMELINE_PLUS_OUTLINE("mdit-timeline-plus-outline", "F0F97"),
    TIMELINE_REMOVE("mdit-timeline-remove", "F1536"),
    TIMELINE_REMOVE_OUTLINE("mdit-timeline-remove-outline", "F1537"),
    TIMELINE_TEXT("mdit-timeline-text", "F0BD3"),
    TIMELINE_TEXT_OUTLINE("mdit-timeline-text-outline", "F0BD4"),
    TIMER("mdit-timer", "F13AB"),
    TIMER_10("mdit-timer-10", "F051C"),
    TIMER_3("mdit-timer-3", "F051D"),
    TIMER_OFF("mdit-timer-off", "F13AC"),
    TIMER_OFF_OUTLINE("mdit-timer-off-outline", "F051E"),
    TIMER_OUTLINE("mdit-timer-outline", "F051B"),
    TIMER_SAND("mdit-timer-sand", "F051F"),
    TIMER_SAND_EMPTY("mdit-timer-sand-empty", "F06AD"),
    TIMER_SAND_FULL("mdit-timer-sand-full", "F078C"),
    TIMETABLE("mdit-timetable", "F0520"),
    TOASTER("mdit-toaster", "F1063"),
    TOASTER_OFF("mdit-toaster-off", "F11B7"),
    TOASTER_OVEN("mdit-toaster-oven", "F0CD3"),
    TOGGLE_SWITCH("mdit-toggle-switch", "F0521"),
    TOGGLE_SWITCH_OFF("mdit-toggle-switch-off", "F0522"),
    TOGGLE_SWITCH_OFF_OUTLINE("mdit-toggle-switch-off-outline", "F0A19"),
    TOGGLE_SWITCH_OUTLINE("mdit-toggle-switch-outline", "F0A1A"),
    TOILET("mdit-toilet", "F09AB"),
    TOOLBOX("mdit-toolbox", "F09AC"),
    TOOLBOX_OUTLINE("mdit-toolbox-outline", "F09AD"),
    TOOLS("mdit-tools", "F1064"),
    TOOLTIP("mdit-tooltip", "F0523"),
    TOOLTIP_ACCOUNT("mdit-tooltip-account", "F000C"),
    TOOLTIP_CHECK("mdit-tooltip-check", "F155C"),
    TOOLTIP_CHECK_OUTLINE("mdit-tooltip-check-outline", "F155D"),
    TOOLTIP_EDIT("mdit-tooltip-edit", "F0524"),
    TOOLTIP_EDIT_OUTLINE("mdit-tooltip-edit-outline", "F12C5"),
    TOOLTIP_IMAGE("mdit-tooltip-image", "F0525"),
    TOOLTIP_IMAGE_OUTLINE("mdit-tooltip-image-outline", "F0BD5"),
    TOOLTIP_MINUS("mdit-tooltip-minus", "F155E"),
    TOOLTIP_MINUS_OUTLINE("mdit-tooltip-minus-outline", "F155F"),
    TOOLTIP_OUTLINE("mdit-tooltip-outline", "F0526"),
    TOOLTIP_PLUS("mdit-tooltip-plus", "F0BD6"),
    TOOLTIP_PLUS_OUTLINE("mdit-tooltip-plus-outline", "F0527"),
    TOOLTIP_REMOVE("mdit-tooltip-remove", "F1560"),
    TOOLTIP_REMOVE_OUTLINE("mdit-tooltip-remove-outline", "F1561"),
    TOOLTIP_TEXT("mdit-tooltip-text", "F0528"),
    TOOLTIP_TEXT_OUTLINE("mdit-tooltip-text-outline", "F0BD7"),
    TOOTH("mdit-tooth", "F08C3"),
    TOOTH_OUTLINE("mdit-tooth-outline", "F0529"),
    TOOTHBRUSH("mdit-toothbrush", "F1129"),
    TOOTHBRUSH_ELECTRIC("mdit-toothbrush-electric", "F112C"),
    TOOTHBRUSH_PASTE("mdit-toothbrush-paste", "F112A"),
    TORCH("mdit-torch", "F1606"),
    TORTOISE("mdit-tortoise", "F0D3B"),
    TOSLINK("mdit-toslink", "F12B8"),
    TOURNAMENT("mdit-tournament", "F09AE"),
    TOW_TRUCK("mdit-tow-truck", "F083C"),
    TOWER_BEACH("mdit-tower-beach", "F0681"),
    TOWER_FIRE("mdit-tower-fire", "F0682"),
    TOY_BRICK("mdit-toy-brick", "F1288"),
    TOY_BRICK_MARKER("mdit-toy-brick-marker", "F1289"),
    TOY_BRICK_MARKER_OUTLINE("mdit-toy-brick-marker-outline", "F128A"),
    TOY_BRICK_MINUS("mdit-toy-brick-minus", "F128B"),
    TOY_BRICK_MINUS_OUTLINE("mdit-toy-brick-minus-outline", "F128C"),
    TOY_BRICK_OUTLINE("mdit-toy-brick-outline", "F128D"),
    TOY_BRICK_PLUS("mdit-toy-brick-plus", "F128E"),
    TOY_BRICK_PLUS_OUTLINE("mdit-toy-brick-plus-outline", "F128F"),
    TOY_BRICK_REMOVE("mdit-toy-brick-remove", "F1290"),
    TOY_BRICK_REMOVE_OUTLINE("mdit-toy-brick-remove-outline", "F1291"),
    TOY_BRICK_SEARCH("mdit-toy-brick-search", "F1292"),
    TOY_BRICK_SEARCH_OUTLINE("mdit-toy-brick-search-outline", "F1293"),
    TRACK_LIGHT("mdit-track-light", "F0914"),
    TRACKPAD("mdit-trackpad", "F07F8"),
    TRACKPAD_LOCK("mdit-trackpad-lock", "F0933"),
    TRACTOR("mdit-tractor", "F0892"),
    TRACTOR_VARIANT("mdit-tractor-variant", "F14C4"),
    TRADEMARK("mdit-trademark", "F0A78"),
    TRAFFIC_CONE("mdit-traffic-cone", "F137C"),
    TRAFFIC_LIGHT("mdit-traffic-light", "F052B"),
    TRAIN("mdit-train", "F052C"),
    TRAIN_CAR("mdit-train-car", "F0BD8"),
    TRAIN_VARIANT("mdit-train-variant", "F08C4"),
    TRAM("mdit-tram", "F052D"),
    TRAM_SIDE("mdit-tram-side", "F0FE7"),
    TRANSCRIBE("mdit-transcribe", "F052E"),
    TRANSCRIBE_CLOSE("mdit-transcribe-close", "F052F"),
    TRANSFER("mdit-transfer", "F1065"),
    TRANSFER_DOWN("mdit-transfer-down", "F0DA1"),
    TRANSFER_LEFT("mdit-transfer-left", "F0DA2"),
    TRANSFER_RIGHT("mdit-transfer-right", "F0530"),
    TRANSFER_UP("mdit-transfer-up", "F0DA3"),
    TRANSIT_CONNECTION("mdit-transit-connection", "F0D3C"),
    TRANSIT_CONNECTION_HORIZONTAL("mdit-transit-connection-horizontal", "F1546"),
    TRANSIT_CONNECTION_VARIANT("mdit-transit-connection-variant", "F0D3D"),
    TRANSIT_DETOUR("mdit-transit-detour", "F0F8B"),
    TRANSIT_SKIP("mdit-transit-skip", "F1515"),
    TRANSIT_TRANSFER("mdit-transit-transfer", "F06AE"),
    TRANSITION("mdit-transition", "F0915"),
    TRANSITION_MASKED("mdit-transition-masked", "F0916"),
    TRANSLATE("mdit-translate", "F05CA"),
    TRANSLATE_OFF("mdit-translate-off", "F0E06"),
    TRANSMISSION_TOWER("mdit-transmission-tower", "F0D3E"),
    TRASH_CAN("mdit-trash-can", "F0A79"),
    TRASH_CAN_OUTLINE("mdit-trash-can-outline", "F0A7A"),
    TRAY("mdit-tray", "F1294"),
    TRAY_ALERT("mdit-tray-alert", "F1295"),
    TRAY_FULL("mdit-tray-full", "F1296"),
    TRAY_MINUS("mdit-tray-minus", "F1297"),
    TRAY_PLUS("mdit-tray-plus", "F1298"),
    TRAY_REMOVE("mdit-tray-remove", "F1299"),
    TREASURE_CHEST("mdit-treasure-chest", "F0726"),
    TREE("mdit-tree", "F0531"),
    TREE_OUTLINE("mdit-tree-outline", "F0E69"),
    TRELLO("mdit-trello", "F0532"),
    TRENDING_DOWN("mdit-trending-down", "F0533"),
    TRENDING_NEUTRAL("mdit-trending-neutral", "F0534"),
    TRENDING_UP("mdit-trending-up", "F0535"),
    TRIANGLE("mdit-triangle", "F0536"),
    TRIANGLE_OUTLINE("mdit-triangle-outline", "F0537"),
    TRIANGLE_WAVE("mdit-triangle-wave", "F147C"),
    TRIFORCE("mdit-triforce", "F0BD9"),
    TROPHY("mdit-trophy", "F0538"),
    TROPHY_AWARD("mdit-trophy-award", "F0539"),
    TROPHY_BROKEN("mdit-trophy-broken", "F0DA4"),
    TROPHY_OUTLINE("mdit-trophy-outline", "F053A"),
    TROPHY_VARIANT("mdit-trophy-variant", "F053B"),
    TROPHY_VARIANT_OUTLINE("mdit-trophy-variant-outline", "F053C"),
    TRUCK("mdit-truck", "F053D"),
    TRUCK_CHECK("mdit-truck-check", "F0CD4"),
    TRUCK_CHECK_OUTLINE("mdit-truck-check-outline", "F129A"),
    TRUCK_DELIVERY("mdit-truck-delivery", "F053E"),
    TRUCK_DELIVERY_OUTLINE("mdit-truck-delivery-outline", "F129B"),
    TRUCK_FAST("mdit-truck-fast", "F0788"),
    TRUCK_FAST_OUTLINE("mdit-truck-fast-outline", "F129C"),
    TRUCK_OUTLINE("mdit-truck-outline", "F129D"),
    TRUCK_TRAILER("mdit-truck-trailer", "F0727"),
    TRUMPET("mdit-trumpet", "F1096"),
    TSHIRT_CREW("mdit-tshirt-crew", "F0A7B"),
    TSHIRT_CREW_OUTLINE("mdit-tshirt-crew-outline", "F053F"),
    TSHIRT_V("mdit-tshirt-v", "F0A7C"),
    TSHIRT_V_OUTLINE("mdit-tshirt-v-outline", "F0540"),
    TUMBLE_DRYER("mdit-tumble-dryer", "F0917"),
    TUMBLE_DRYER_ALERT("mdit-tumble-dryer-alert", "F11BA"),
    TUMBLE_DRYER_OFF("mdit-tumble-dryer-off", "F11BB"),
    TUNE("mdit-tune", "F062E"),
    TUNE_VARIANT("mdit-tune-variant", "F1542"),
    TUNE_VERTICAL("mdit-tune-vertical", "F066A"),
    TUNE_VERTICAL_VARIANT("mdit-tune-vertical-variant", "F1543"),
    TURNSTILE("mdit-turnstile", "F0CD5"),
    TURNSTILE_OUTLINE("mdit-turnstile-outline", "F0CD6"),
    TURTLE("mdit-turtle", "F0CD7"),
    TWITCH("mdit-twitch", "F0543"),
    TWITTER("mdit-twitter", "F0544"),
    TWITTER_RETWEET("mdit-twitter-retweet", "F0547"),
    TWO_FACTOR_AUTHENTICATION("mdit-two-factor-authentication", "F09AF"),
    TYPEWRITER("mdit-typewriter", "F0F2D");

    public static MaterialDesignT findByDescription(String description) {
        for (MaterialDesignT font : values()) {
            if (font.getDescription().equals(description)) {
                return font;
            }
        }
        throw new IllegalArgumentException("Icon description '" + description + "' is invalid!");
    }

    private String description;
    private int code;

    MaterialDesignT(String description, String code) {
        this.description = description;
        this.code = Integer.parseInt(code, 16);
    }

    @Override
    public String getDescription() {
        return description;
    }

    @Override
    public int getCode() {
        return code;
    }
}
