/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2015-2020 Andres Almiray
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kordamp.ikonli.materialdesign;

import org.kordamp.ikonli.Ikon;

/**
 * @author Andres Almiray
 */
public enum MaterialDesignM implements Ikon {
    MAGNET("mdim-magnet", "F0347"),
    MAGNET_ON("mdim-magnet-on", "F0348"),
    MAGNIFY("mdim-magnify", "F0349"),
    MAGNIFY_CLOSE("mdim-magnify-close", "F0980"),
    MAGNIFY_MINUS("mdim-magnify-minus", "F034A"),
    MAGNIFY_MINUS_CURSOR("mdim-magnify-minus-cursor", "F0A62"),
    MAGNIFY_MINUS_OUTLINE("mdim-magnify-minus-outline", "F06EC"),
    MAGNIFY_PLUS("mdim-magnify-plus", "F034B"),
    MAGNIFY_PLUS_CURSOR("mdim-magnify-plus-cursor", "F0A63"),
    MAGNIFY_PLUS_OUTLINE("mdim-magnify-plus-outline", "F06ED"),
    MAGNIFY_REMOVE_CURSOR("mdim-magnify-remove-cursor", "F120C"),
    MAGNIFY_REMOVE_OUTLINE("mdim-magnify-remove-outline", "F120D"),
    MAGNIFY_SCAN("mdim-magnify-scan", "F1276"),
    MAIL("mdim-mail", "F0EBB"),
    MAILBOX("mdim-mailbox", "F06EE"),
    MAILBOX_OPEN("mdim-mailbox-open", "F0D88"),
    MAILBOX_OPEN_OUTLINE("mdim-mailbox-open-outline", "F0D89"),
    MAILBOX_OPEN_UP("mdim-mailbox-open-up", "F0D8A"),
    MAILBOX_OPEN_UP_OUTLINE("mdim-mailbox-open-up-outline", "F0D8B"),
    MAILBOX_OUTLINE("mdim-mailbox-outline", "F0D8C"),
    MAILBOX_UP("mdim-mailbox-up", "F0D8D"),
    MAILBOX_UP_OUTLINE("mdim-mailbox-up-outline", "F0D8E"),
    MANJARO("mdim-manjaro", "F160A"),
    MAP("mdim-map", "F034D"),
    MAP_CHECK("mdim-map-check", "F0EBC"),
    MAP_CHECK_OUTLINE("mdim-map-check-outline", "F0EBD"),
    MAP_CLOCK("mdim-map-clock", "F0D1E"),
    MAP_CLOCK_OUTLINE("mdim-map-clock-outline", "F0D1F"),
    MAP_LEGEND("mdim-map-legend", "F0A01"),
    MAP_MARKER("mdim-map-marker", "F034E"),
    MAP_MARKER_ALERT("mdim-map-marker-alert", "F0F05"),
    MAP_MARKER_ALERT_OUTLINE("mdim-map-marker-alert-outline", "F0F06"),
    MAP_MARKER_CHECK("mdim-map-marker-check", "F0C95"),
    MAP_MARKER_CHECK_OUTLINE("mdim-map-marker-check-outline", "F12FB"),
    MAP_MARKER_CIRCLE("mdim-map-marker-circle", "F034F"),
    MAP_MARKER_DISTANCE("mdim-map-marker-distance", "F08F0"),
    MAP_MARKER_DOWN("mdim-map-marker-down", "F1102"),
    MAP_MARKER_LEFT("mdim-map-marker-left", "F12DB"),
    MAP_MARKER_LEFT_OUTLINE("mdim-map-marker-left-outline", "F12DD"),
    MAP_MARKER_MINUS("mdim-map-marker-minus", "F0650"),
    MAP_MARKER_MINUS_OUTLINE("mdim-map-marker-minus-outline", "F12F9"),
    MAP_MARKER_MULTIPLE("mdim-map-marker-multiple", "F0350"),
    MAP_MARKER_MULTIPLE_OUTLINE("mdim-map-marker-multiple-outline", "F1277"),
    MAP_MARKER_OFF("mdim-map-marker-off", "F0351"),
    MAP_MARKER_OFF_OUTLINE("mdim-map-marker-off-outline", "F12FD"),
    MAP_MARKER_OUTLINE("mdim-map-marker-outline", "F07D9"),
    MAP_MARKER_PATH("mdim-map-marker-path", "F0D20"),
    MAP_MARKER_PLUS("mdim-map-marker-plus", "F0651"),
    MAP_MARKER_PLUS_OUTLINE("mdim-map-marker-plus-outline", "F12F8"),
    MAP_MARKER_QUESTION("mdim-map-marker-question", "F0F07"),
    MAP_MARKER_QUESTION_OUTLINE("mdim-map-marker-question-outline", "F0F08"),
    MAP_MARKER_RADIUS("mdim-map-marker-radius", "F0352"),
    MAP_MARKER_RADIUS_OUTLINE("mdim-map-marker-radius-outline", "F12FC"),
    MAP_MARKER_REMOVE("mdim-map-marker-remove", "F0F09"),
    MAP_MARKER_REMOVE_OUTLINE("mdim-map-marker-remove-outline", "F12FA"),
    MAP_MARKER_REMOVE_VARIANT("mdim-map-marker-remove-variant", "F0F0A"),
    MAP_MARKER_RIGHT("mdim-map-marker-right", "F12DC"),
    MAP_MARKER_RIGHT_OUTLINE("mdim-map-marker-right-outline", "F12DE"),
    MAP_MARKER_STAR("mdim-map-marker-star", "F1608"),
    MAP_MARKER_STAR_OUTLINE("mdim-map-marker-star-outline", "F1609"),
    MAP_MARKER_UP("mdim-map-marker-up", "F1103"),
    MAP_MINUS("mdim-map-minus", "F0981"),
    MAP_OUTLINE("mdim-map-outline", "F0982"),
    MAP_PLUS("mdim-map-plus", "F0983"),
    MAP_SEARCH("mdim-map-search", "F0984"),
    MAP_SEARCH_OUTLINE("mdim-map-search-outline", "F0985"),
    MAPBOX("mdim-mapbox", "F0BAA"),
    MARGIN("mdim-margin", "F0353"),
    MARKER("mdim-marker", "F0652"),
    MARKER_CANCEL("mdim-marker-cancel", "F0DD9"),
    MARKER_CHECK("mdim-marker-check", "F0355"),
    MASTODON("mdim-mastodon", "F0AD1"),
    MATERIAL_DESIGN("mdim-material-design", "F0986"),
    MATERIAL_UI("mdim-material-ui", "F0357"),
    MATH_COMPASS("mdim-math-compass", "F0358"),
    MATH_COS("mdim-math-cos", "F0C96"),
    MATH_INTEGRAL("mdim-math-integral", "F0FC8"),
    MATH_INTEGRAL_BOX("mdim-math-integral-box", "F0FC9"),
    MATH_LOG("mdim-math-log", "F1085"),
    MATH_NORM("mdim-math-norm", "F0FCA"),
    MATH_NORM_BOX("mdim-math-norm-box", "F0FCB"),
    MATH_SIN("mdim-math-sin", "F0C97"),
    MATH_TAN("mdim-math-tan", "F0C98"),
    MATRIX("mdim-matrix", "F0628"),
    MEDAL("mdim-medal", "F0987"),
    MEDAL_OUTLINE("mdim-medal-outline", "F1326"),
    MEDICAL_BAG("mdim-medical-bag", "F06EF"),
    MEDITATION("mdim-meditation", "F117B"),
    MEMORY("mdim-memory", "F035B"),
    MENU("mdim-menu", "F035C"),
    MENU_DOWN("mdim-menu-down", "F035D"),
    MENU_DOWN_OUTLINE("mdim-menu-down-outline", "F06B6"),
    MENU_LEFT("mdim-menu-left", "F035E"),
    MENU_LEFT_OUTLINE("mdim-menu-left-outline", "F0A02"),
    MENU_OPEN("mdim-menu-open", "F0BAB"),
    MENU_RIGHT("mdim-menu-right", "F035F"),
    MENU_RIGHT_OUTLINE("mdim-menu-right-outline", "F0A03"),
    MENU_SWAP("mdim-menu-swap", "F0A64"),
    MENU_SWAP_OUTLINE("mdim-menu-swap-outline", "F0A65"),
    MENU_UP("mdim-menu-up", "F0360"),
    MENU_UP_OUTLINE("mdim-menu-up-outline", "F06B7"),
    MERGE("mdim-merge", "F0F5C"),
    MESSAGE("mdim-message", "F0361"),
    MESSAGE_ALERT("mdim-message-alert", "F0362"),
    MESSAGE_ALERT_OUTLINE("mdim-message-alert-outline", "F0A04"),
    MESSAGE_ARROW_LEFT("mdim-message-arrow-left", "F12F2"),
    MESSAGE_ARROW_LEFT_OUTLINE("mdim-message-arrow-left-outline", "F12F3"),
    MESSAGE_ARROW_RIGHT("mdim-message-arrow-right", "F12F4"),
    MESSAGE_ARROW_RIGHT_OUTLINE("mdim-message-arrow-right-outline", "F12F5"),
    MESSAGE_BOOKMARK("mdim-message-bookmark", "F15AC"),
    MESSAGE_BOOKMARK_OUTLINE("mdim-message-bookmark-outline", "F15AD"),
    MESSAGE_BULLETED("mdim-message-bulleted", "F06A2"),
    MESSAGE_BULLETED_OFF("mdim-message-bulleted-off", "F06A3"),
    MESSAGE_COG("mdim-message-cog", "F06F1"),
    MESSAGE_COG_OUTLINE("mdim-message-cog-outline", "F1172"),
    MESSAGE_DRAW("mdim-message-draw", "F0363"),
    MESSAGE_FLASH("mdim-message-flash", "F15A9"),
    MESSAGE_FLASH_OUTLINE("mdim-message-flash-outline", "F15AA"),
    MESSAGE_IMAGE("mdim-message-image", "F0364"),
    MESSAGE_IMAGE_OUTLINE("mdim-message-image-outline", "F116C"),
    MESSAGE_LOCK("mdim-message-lock", "F0FCC"),
    MESSAGE_LOCK_OUTLINE("mdim-message-lock-outline", "F116D"),
    MESSAGE_MINUS("mdim-message-minus", "F116E"),
    MESSAGE_MINUS_OUTLINE("mdim-message-minus-outline", "F116F"),
    MESSAGE_OFF("mdim-message-off", "F164D"),
    MESSAGE_OFF_OUTLINE("mdim-message-off-outline", "F164E"),
    MESSAGE_OUTLINE("mdim-message-outline", "F0365"),
    MESSAGE_PLUS("mdim-message-plus", "F0653"),
    MESSAGE_PLUS_OUTLINE("mdim-message-plus-outline", "F10BB"),
    MESSAGE_PROCESSING("mdim-message-processing", "F0366"),
    MESSAGE_PROCESSING_OUTLINE("mdim-message-processing-outline", "F1170"),
    MESSAGE_REPLY("mdim-message-reply", "F0367"),
    MESSAGE_REPLY_TEXT("mdim-message-reply-text", "F0368"),
    MESSAGE_SETTINGS("mdim-message-settings", "F06F0"),
    MESSAGE_SETTINGS_OUTLINE("mdim-message-settings-outline", "F1171"),
    MESSAGE_TEXT("mdim-message-text", "F0369"),
    MESSAGE_TEXT_CLOCK("mdim-message-text-clock", "F1173"),
    MESSAGE_TEXT_CLOCK_OUTLINE("mdim-message-text-clock-outline", "F1174"),
    MESSAGE_TEXT_LOCK("mdim-message-text-lock", "F0FCD"),
    MESSAGE_TEXT_LOCK_OUTLINE("mdim-message-text-lock-outline", "F1175"),
    MESSAGE_TEXT_OUTLINE("mdim-message-text-outline", "F036A"),
    MESSAGE_VIDEO("mdim-message-video", "F036B"),
    METEOR("mdim-meteor", "F0629"),
    METRONOME("mdim-metronome", "F07DA"),
    METRONOME_TICK("mdim-metronome-tick", "F07DB"),
    MICRO_SD("mdim-micro-sd", "F07DC"),
    MICROPHONE("mdim-microphone", "F036C"),
    MICROPHONE_MINUS("mdim-microphone-minus", "F08B3"),
    MICROPHONE_OFF("mdim-microphone-off", "F036D"),
    MICROPHONE_OUTLINE("mdim-microphone-outline", "F036E"),
    MICROPHONE_PLUS("mdim-microphone-plus", "F08B4"),
    MICROPHONE_SETTINGS("mdim-microphone-settings", "F036F"),
    MICROPHONE_VARIANT("mdim-microphone-variant", "F0370"),
    MICROPHONE_VARIANT_OFF("mdim-microphone-variant-off", "F0371"),
    MICROSCOPE("mdim-microscope", "F0654"),
    MICROSOFT("mdim-microsoft", "F0372"),
    MICROSOFT_ACCESS("mdim-microsoft-access", "F138E"),
    MICROSOFT_AZURE("mdim-microsoft-azure", "F0805"),
    MICROSOFT_AZURE_DEVOPS("mdim-microsoft-azure-devops", "F0FD5"),
    MICROSOFT_BING("mdim-microsoft-bing", "F00A4"),
    MICROSOFT_DYNAMICS_365("mdim-microsoft-dynamics-365", "F0988"),
    MICROSOFT_EDGE("mdim-microsoft-edge", "F01E9"),
    MICROSOFT_EDGE_LEGACY("mdim-microsoft-edge-legacy", "F1250"),
    MICROSOFT_EXCEL("mdim-microsoft-excel", "F138F"),
    MICROSOFT_INTERNET_EXPLORER("mdim-microsoft-internet-explorer", "F0300"),
    MICROSOFT_OFFICE("mdim-microsoft-office", "F03C6"),
    MICROSOFT_ONEDRIVE("mdim-microsoft-onedrive", "F03CA"),
    MICROSOFT_ONENOTE("mdim-microsoft-onenote", "F0747"),
    MICROSOFT_OUTLOOK("mdim-microsoft-outlook", "F0D22"),
    MICROSOFT_POWERPOINT("mdim-microsoft-powerpoint", "F1390"),
    MICROSOFT_SHAREPOINT("mdim-microsoft-sharepoint", "F1391"),
    MICROSOFT_TEAMS("mdim-microsoft-teams", "F02BB"),
    MICROSOFT_VISUAL_STUDIO("mdim-microsoft-visual-studio", "F0610"),
    MICROSOFT_VISUAL_STUDIO_CODE("mdim-microsoft-visual-studio-code", "F0A1E"),
    MICROSOFT_WINDOWS("mdim-microsoft-windows", "F05B3"),
    MICROSOFT_WINDOWS_CLASSIC("mdim-microsoft-windows-classic", "F0A21"),
    MICROSOFT_WORD("mdim-microsoft-word", "F1392"),
    MICROSOFT_XBOX("mdim-microsoft-xbox", "F05B9"),
    MICROSOFT_XBOX_CONTROLLER("mdim-microsoft-xbox-controller", "F05BA"),
    MICROSOFT_XBOX_CONTROLLER_BATTERY_ALERT("mdim-microsoft-xbox-controller-battery-alert", "F074B"),
    MICROSOFT_XBOX_CONTROLLER_BATTERY_CHARGING("mdim-microsoft-xbox-controller-battery-charging", "F0A22"),
    MICROSOFT_XBOX_CONTROLLER_BATTERY_EMPTY("mdim-microsoft-xbox-controller-battery-empty", "F074C"),
    MICROSOFT_XBOX_CONTROLLER_BATTERY_FULL("mdim-microsoft-xbox-controller-battery-full", "F074D"),
    MICROSOFT_XBOX_CONTROLLER_BATTERY_LOW("mdim-microsoft-xbox-controller-battery-low", "F074E"),
    MICROSOFT_XBOX_CONTROLLER_BATTERY_MEDIUM("mdim-microsoft-xbox-controller-battery-medium", "F074F"),
    MICROSOFT_XBOX_CONTROLLER_BATTERY_UNKNOWN("mdim-microsoft-xbox-controller-battery-unknown", "F0750"),
    MICROSOFT_XBOX_CONTROLLER_MENU("mdim-microsoft-xbox-controller-menu", "F0E6F"),
    MICROSOFT_XBOX_CONTROLLER_OFF("mdim-microsoft-xbox-controller-off", "F05BB"),
    MICROSOFT_XBOX_CONTROLLER_VIEW("mdim-microsoft-xbox-controller-view", "F0E70"),
    MICROSOFT_YAMMER("mdim-microsoft-yammer", "F0789"),
    MICROWAVE("mdim-microwave", "F0C99"),
    MICROWAVE_OFF("mdim-microwave-off", "F1423"),
    MIDDLEWARE("mdim-middleware", "F0F5D"),
    MIDDLEWARE_OUTLINE("mdim-middleware-outline", "F0F5E"),
    MIDI("mdim-midi", "F08F1"),
    MIDI_PORT("mdim-midi-port", "F08F2"),
    MINE("mdim-mine", "F0DDA"),
    MINECRAFT("mdim-minecraft", "F0373"),
    MINI_SD("mdim-mini-sd", "F0A05"),
    MINIDISC("mdim-minidisc", "F0A06"),
    MINUS("mdim-minus", "F0374"),
    MINUS_BOX("mdim-minus-box", "F0375"),
    MINUS_BOX_MULTIPLE("mdim-minus-box-multiple", "F1141"),
    MINUS_BOX_MULTIPLE_OUTLINE("mdim-minus-box-multiple-outline", "F1142"),
    MINUS_BOX_OUTLINE("mdim-minus-box-outline", "F06F2"),
    MINUS_CIRCLE("mdim-minus-circle", "F0376"),
    MINUS_CIRCLE_MULTIPLE("mdim-minus-circle-multiple", "F035A"),
    MINUS_CIRCLE_MULTIPLE_OUTLINE("mdim-minus-circle-multiple-outline", "F0AD3"),
    MINUS_CIRCLE_OFF("mdim-minus-circle-off", "F1459"),
    MINUS_CIRCLE_OFF_OUTLINE("mdim-minus-circle-off-outline", "F145A"),
    MINUS_CIRCLE_OUTLINE("mdim-minus-circle-outline", "F0377"),
    MINUS_NETWORK("mdim-minus-network", "F0378"),
    MINUS_NETWORK_OUTLINE("mdim-minus-network-outline", "F0C9A"),
    MINUS_THICK("mdim-minus-thick", "F1639"),
    MIRROR("mdim-mirror", "F11FD"),
    MIXED_MARTIAL_ARTS("mdim-mixed-martial-arts", "F0D8F"),
    MIXED_REALITY("mdim-mixed-reality", "F087F"),
    MOLECULE("mdim-molecule", "F0BAC"),
    MOLECULE_CO("mdim-molecule-co", "F12FE"),
    MOLECULE_CO2("mdim-molecule-co2", "F07E4"),
    MONITOR("mdim-monitor", "F0379"),
    MONITOR_CELLPHONE("mdim-monitor-cellphone", "F0989"),
    MONITOR_CELLPHONE_STAR("mdim-monitor-cellphone-star", "F098A"),
    MONITOR_CLEAN("mdim-monitor-clean", "F1104"),
    MONITOR_DASHBOARD("mdim-monitor-dashboard", "F0A07"),
    MONITOR_EDIT("mdim-monitor-edit", "F12C6"),
    MONITOR_EYE("mdim-monitor-eye", "F13B4"),
    MONITOR_LOCK("mdim-monitor-lock", "F0DDB"),
    MONITOR_MULTIPLE("mdim-monitor-multiple", "F037A"),
    MONITOR_OFF("mdim-monitor-off", "F0D90"),
    MONITOR_SCREENSHOT("mdim-monitor-screenshot", "F0E51"),
    MONITOR_SHARE("mdim-monitor-share", "F1483"),
    MONITOR_SPEAKER("mdim-monitor-speaker", "F0F5F"),
    MONITOR_SPEAKER_OFF("mdim-monitor-speaker-off", "F0F60"),
    MONITOR_STAR("mdim-monitor-star", "F0DDC"),
    MOON_FIRST_QUARTER("mdim-moon-first-quarter", "F0F61"),
    MOON_FULL("mdim-moon-full", "F0F62"),
    MOON_LAST_QUARTER("mdim-moon-last-quarter", "F0F63"),
    MOON_NEW("mdim-moon-new", "F0F64"),
    MOON_WANING_CRESCENT("mdim-moon-waning-crescent", "F0F65"),
    MOON_WANING_GIBBOUS("mdim-moon-waning-gibbous", "F0F66"),
    MOON_WAXING_CRESCENT("mdim-moon-waxing-crescent", "F0F67"),
    MOON_WAXING_GIBBOUS("mdim-moon-waxing-gibbous", "F0F68"),
    MOPED("mdim-moped", "F1086"),
    MOPED_ELECTRIC("mdim-moped-electric", "F15B7"),
    MOPED_ELECTRIC_OUTLINE("mdim-moped-electric-outline", "F15B8"),
    MOPED_OUTLINE("mdim-moped-outline", "F15B9"),
    MORE("mdim-more", "F037B"),
    MOTHER_HEART("mdim-mother-heart", "F1314"),
    MOTHER_NURSE("mdim-mother-nurse", "F0D21"),
    MOTION("mdim-motion", "F15B2"),
    MOTION_OUTLINE("mdim-motion-outline", "F15B3"),
    MOTION_PAUSE("mdim-motion-pause", "F1590"),
    MOTION_PAUSE_OUTLINE("mdim-motion-pause-outline", "F1592"),
    MOTION_PLAY("mdim-motion-play", "F158F"),
    MOTION_PLAY_OUTLINE("mdim-motion-play-outline", "F1591"),
    MOTION_SENSOR("mdim-motion-sensor", "F0D91"),
    MOTION_SENSOR_OFF("mdim-motion-sensor-off", "F1435"),
    MOTORBIKE("mdim-motorbike", "F037C"),
    MOTORBIKE_ELECTRIC("mdim-motorbike-electric", "F15BA"),
    MOUSE("mdim-mouse", "F037D"),
    MOUSE_BLUETOOTH("mdim-mouse-bluetooth", "F098B"),
    MOUSE_MOVE_DOWN("mdim-mouse-move-down", "F1550"),
    MOUSE_MOVE_UP("mdim-mouse-move-up", "F1551"),
    MOUSE_MOVE_VERTICAL("mdim-mouse-move-vertical", "F1552"),
    MOUSE_OFF("mdim-mouse-off", "F037E"),
    MOUSE_VARIANT("mdim-mouse-variant", "F037F"),
    MOUSE_VARIANT_OFF("mdim-mouse-variant-off", "F0380"),
    MOVE_RESIZE("mdim-move-resize", "F0655"),
    MOVE_RESIZE_VARIANT("mdim-move-resize-variant", "F0656"),
    MOVIE("mdim-movie", "F0381"),
    MOVIE_EDIT("mdim-movie-edit", "F1122"),
    MOVIE_EDIT_OUTLINE("mdim-movie-edit-outline", "F1123"),
    MOVIE_FILTER("mdim-movie-filter", "F1124"),
    MOVIE_FILTER_OUTLINE("mdim-movie-filter-outline", "F1125"),
    MOVIE_OPEN("mdim-movie-open", "F0FCE"),
    MOVIE_OPEN_OUTLINE("mdim-movie-open-outline", "F0FCF"),
    MOVIE_OUTLINE("mdim-movie-outline", "F0DDD"),
    MOVIE_ROLL("mdim-movie-roll", "F07DE"),
    MOVIE_SEARCH("mdim-movie-search", "F11D2"),
    MOVIE_SEARCH_OUTLINE("mdim-movie-search-outline", "F11D3"),
    MOWER("mdim-mower", "F166F"),
    MOWER_BAG("mdim-mower-bag", "F1670"),
    MUFFIN("mdim-muffin", "F098C"),
    MULTIPLICATION("mdim-multiplication", "F0382"),
    MULTIPLICATION_BOX("mdim-multiplication-box", "F0383"),
    MUSHROOM("mdim-mushroom", "F07DF"),
    MUSHROOM_OFF("mdim-mushroom-off", "F13FA"),
    MUSHROOM_OFF_OUTLINE("mdim-mushroom-off-outline", "F13FB"),
    MUSHROOM_OUTLINE("mdim-mushroom-outline", "F07E0"),
    MUSIC("mdim-music", "F075A"),
    MUSIC_ACCIDENTAL_DOUBLE_FLAT("mdim-music-accidental-double-flat", "F0F69"),
    MUSIC_ACCIDENTAL_DOUBLE_SHARP("mdim-music-accidental-double-sharp", "F0F6A"),
    MUSIC_ACCIDENTAL_FLAT("mdim-music-accidental-flat", "F0F6B"),
    MUSIC_ACCIDENTAL_NATURAL("mdim-music-accidental-natural", "F0F6C"),
    MUSIC_ACCIDENTAL_SHARP("mdim-music-accidental-sharp", "F0F6D"),
    MUSIC_BOX("mdim-music-box", "F0384"),
    MUSIC_BOX_MULTIPLE("mdim-music-box-multiple", "F0333"),
    MUSIC_BOX_MULTIPLE_OUTLINE("mdim-music-box-multiple-outline", "F0F04"),
    MUSIC_BOX_OUTLINE("mdim-music-box-outline", "F0385"),
    MUSIC_CIRCLE("mdim-music-circle", "F0386"),
    MUSIC_CIRCLE_OUTLINE("mdim-music-circle-outline", "F0AD4"),
    MUSIC_CLEF_ALTO("mdim-music-clef-alto", "F0F6E"),
    MUSIC_CLEF_BASS("mdim-music-clef-bass", "F0F6F"),
    MUSIC_CLEF_TREBLE("mdim-music-clef-treble", "F0F70"),
    MUSIC_NOTE("mdim-music-note", "F0387"),
    MUSIC_NOTE_BLUETOOTH("mdim-music-note-bluetooth", "F05FE"),
    MUSIC_NOTE_BLUETOOTH_OFF("mdim-music-note-bluetooth-off", "F05FF"),
    MUSIC_NOTE_EIGHTH("mdim-music-note-eighth", "F0388"),
    MUSIC_NOTE_EIGHTH_DOTTED("mdim-music-note-eighth-dotted", "F0F71"),
    MUSIC_NOTE_HALF("mdim-music-note-half", "F0389"),
    MUSIC_NOTE_HALF_DOTTED("mdim-music-note-half-dotted", "F0F72"),
    MUSIC_NOTE_OFF("mdim-music-note-off", "F038A"),
    MUSIC_NOTE_OFF_OUTLINE("mdim-music-note-off-outline", "F0F73"),
    MUSIC_NOTE_OUTLINE("mdim-music-note-outline", "F0F74"),
    MUSIC_NOTE_PLUS("mdim-music-note-plus", "F0DDE"),
    MUSIC_NOTE_QUARTER("mdim-music-note-quarter", "F038B"),
    MUSIC_NOTE_QUARTER_DOTTED("mdim-music-note-quarter-dotted", "F0F75"),
    MUSIC_NOTE_SIXTEENTH("mdim-music-note-sixteenth", "F038C"),
    MUSIC_NOTE_SIXTEENTH_DOTTED("mdim-music-note-sixteenth-dotted", "F0F76"),
    MUSIC_NOTE_WHOLE("mdim-music-note-whole", "F038D"),
    MUSIC_NOTE_WHOLE_DOTTED("mdim-music-note-whole-dotted", "F0F77"),
    MUSIC_OFF("mdim-music-off", "F075B"),
    MUSIC_REST_EIGHTH("mdim-music-rest-eighth", "F0F78"),
    MUSIC_REST_HALF("mdim-music-rest-half", "F0F79"),
    MUSIC_REST_QUARTER("mdim-music-rest-quarter", "F0F7A"),
    MUSIC_REST_SIXTEENTH("mdim-music-rest-sixteenth", "F0F7B"),
    MUSIC_REST_WHOLE("mdim-music-rest-whole", "F0F7C"),
    MUSTACHE("mdim-mustache", "F15DE");

    public static MaterialDesignM findByDescription(String description) {
        for (MaterialDesignM font : values()) {
            if (font.getDescription().equals(description)) {
                return font;
            }
        }
        throw new IllegalArgumentException("Icon description '" + description + "' is invalid!");
    }

    private String description;
    private int code;

    MaterialDesignM(String description, String code) {
        this.description = description;
        this.code = Integer.parseInt(code, 16);
    }

    @Override
    public String getDescription() {
        return description;
    }

    @Override
    public int getCode() {
        return code;
    }
}
