/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2015-2020 Andres Almiray
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kordamp.ikonli.materialdesign;

import org.kordamp.ikonli.Ikon;

/**
 * @author Andres Almiray
 */
public enum MaterialDesignH implements Ikon {
    HAIL("mdih-hail", "F0AC1"),
    HAIR_DRYER("mdih-hair-dryer", "F10EF"),
    HAIR_DRYER_OUTLINE("mdih-hair-dryer-outline", "F10F0"),
    HALLOWEEN("mdih-halloween", "F0BA3"),
    HAMBURGER("mdih-hamburger", "F0685"),
    HAMMER("mdih-hammer", "F08EA"),
    HAMMER_SCREWDRIVER("mdih-hammer-screwdriver", "F1322"),
    HAMMER_WRENCH("mdih-hammer-wrench", "F1323"),
    HAND("mdih-hand", "F0A4F"),
    HAND_HEART("mdih-hand-heart", "F10F1"),
    HAND_HEART_OUTLINE("mdih-hand-heart-outline", "F157E"),
    HAND_LEFT("mdih-hand-left", "F0E46"),
    HAND_OKAY("mdih-hand-okay", "F0A50"),
    HAND_PEACE("mdih-hand-peace", "F0A51"),
    HAND_PEACE_VARIANT("mdih-hand-peace-variant", "F0A52"),
    HAND_POINTING_DOWN("mdih-hand-pointing-down", "F0A53"),
    HAND_POINTING_LEFT("mdih-hand-pointing-left", "F0A54"),
    HAND_POINTING_RIGHT("mdih-hand-pointing-right", "F02C7"),
    HAND_POINTING_UP("mdih-hand-pointing-up", "F0A55"),
    HAND_RIGHT("mdih-hand-right", "F0E47"),
    HAND_SAW("mdih-hand-saw", "F0E48"),
    HAND_WASH("mdih-hand-wash", "F157F"),
    HAND_WASH_OUTLINE("mdih-hand-wash-outline", "F1580"),
    HAND_WATER("mdih-hand-water", "F139F"),
    HANDBALL("mdih-handball", "F0F53"),
    HANDCUFFS("mdih-handcuffs", "F113E"),
    HANDSHAKE("mdih-handshake", "F1218"),
    HANDSHAKE_OUTLINE("mdih-handshake-outline", "F15A1"),
    HANGER("mdih-hanger", "F02C8"),
    HARD_HAT("mdih-hard-hat", "F096F"),
    HARDDISK("mdih-harddisk", "F02CA"),
    HARDDISK_PLUS("mdih-harddisk-plus", "F104B"),
    HARDDISK_REMOVE("mdih-harddisk-remove", "F104C"),
    HAT_FEDORA("mdih-hat-fedora", "F0BA4"),
    HAZARD_LIGHTS("mdih-hazard-lights", "F0C89"),
    HDR("mdih-hdr", "F0D7D"),
    HDR_OFF("mdih-hdr-off", "F0D7E"),
    HEAD("mdih-head", "F135E"),
    HEAD_ALERT("mdih-head-alert", "F1338"),
    HEAD_ALERT_OUTLINE("mdih-head-alert-outline", "F1339"),
    HEAD_CHECK("mdih-head-check", "F133A"),
    HEAD_CHECK_OUTLINE("mdih-head-check-outline", "F133B"),
    HEAD_COG("mdih-head-cog", "F133C"),
    HEAD_COG_OUTLINE("mdih-head-cog-outline", "F133D"),
    HEAD_DOTS_HORIZONTAL("mdih-head-dots-horizontal", "F133E"),
    HEAD_DOTS_HORIZONTAL_OUTLINE("mdih-head-dots-horizontal-outline", "F133F"),
    HEAD_FLASH("mdih-head-flash", "F1340"),
    HEAD_FLASH_OUTLINE("mdih-head-flash-outline", "F1341"),
    HEAD_HEART("mdih-head-heart", "F1342"),
    HEAD_HEART_OUTLINE("mdih-head-heart-outline", "F1343"),
    HEAD_LIGHTBULB("mdih-head-lightbulb", "F1344"),
    HEAD_LIGHTBULB_OUTLINE("mdih-head-lightbulb-outline", "F1345"),
    HEAD_MINUS("mdih-head-minus", "F1346"),
    HEAD_MINUS_OUTLINE("mdih-head-minus-outline", "F1347"),
    HEAD_OUTLINE("mdih-head-outline", "F135F"),
    HEAD_PLUS("mdih-head-plus", "F1348"),
    HEAD_PLUS_OUTLINE("mdih-head-plus-outline", "F1349"),
    HEAD_QUESTION("mdih-head-question", "F134A"),
    HEAD_QUESTION_OUTLINE("mdih-head-question-outline", "F134B"),
    HEAD_REMOVE("mdih-head-remove", "F134C"),
    HEAD_REMOVE_OUTLINE("mdih-head-remove-outline", "F134D"),
    HEAD_SNOWFLAKE("mdih-head-snowflake", "F134E"),
    HEAD_SNOWFLAKE_OUTLINE("mdih-head-snowflake-outline", "F134F"),
    HEAD_SYNC("mdih-head-sync", "F1350"),
    HEAD_SYNC_OUTLINE("mdih-head-sync-outline", "F1351"),
    HEADPHONES("mdih-headphones", "F02CB"),
    HEADPHONES_BLUETOOTH("mdih-headphones-bluetooth", "F0970"),
    HEADPHONES_BOX("mdih-headphones-box", "F02CC"),
    HEADPHONES_OFF("mdih-headphones-off", "F07CE"),
    HEADPHONES_SETTINGS("mdih-headphones-settings", "F02CD"),
    HEADSET("mdih-headset", "F02CE"),
    HEADSET_DOCK("mdih-headset-dock", "F02CF"),
    HEADSET_OFF("mdih-headset-off", "F02D0"),
    HEART("mdih-heart", "F02D1"),
    HEART_BOX("mdih-heart-box", "F02D2"),
    HEART_BOX_OUTLINE("mdih-heart-box-outline", "F02D3"),
    HEART_BROKEN("mdih-heart-broken", "F02D4"),
    HEART_BROKEN_OUTLINE("mdih-heart-broken-outline", "F0D14"),
    HEART_CIRCLE("mdih-heart-circle", "F0971"),
    HEART_CIRCLE_OUTLINE("mdih-heart-circle-outline", "F0972"),
    HEART_COG("mdih-heart-cog", "F1663"),
    HEART_COG_OUTLINE("mdih-heart-cog-outline", "F1664"),
    HEART_FLASH("mdih-heart-flash", "F0EF9"),
    HEART_HALF("mdih-heart-half", "F06DF"),
    HEART_HALF_FULL("mdih-heart-half-full", "F06DE"),
    HEART_HALF_OUTLINE("mdih-heart-half-outline", "F06E0"),
    HEART_MINUS("mdih-heart-minus", "F142F"),
    HEART_MINUS_OUTLINE("mdih-heart-minus-outline", "F1432"),
    HEART_MULTIPLE("mdih-heart-multiple", "F0A56"),
    HEART_MULTIPLE_OUTLINE("mdih-heart-multiple-outline", "F0A57"),
    HEART_OFF("mdih-heart-off", "F0759"),
    HEART_OFF_OUTLINE("mdih-heart-off-outline", "F1434"),
    HEART_OUTLINE("mdih-heart-outline", "F02D5"),
    HEART_PLUS("mdih-heart-plus", "F142E"),
    HEART_PLUS_OUTLINE("mdih-heart-plus-outline", "F1431"),
    HEART_PULSE("mdih-heart-pulse", "F05F6"),
    HEART_REMOVE("mdih-heart-remove", "F1430"),
    HEART_REMOVE_OUTLINE("mdih-heart-remove-outline", "F1433"),
    HEART_SETTINGS("mdih-heart-settings", "F1665"),
    HEART_SETTINGS_OUTLINE("mdih-heart-settings-outline", "F1666"),
    HELICOPTER("mdih-helicopter", "F0AC2"),
    HELP("mdih-help", "F02D6"),
    HELP_BOX("mdih-help-box", "F078B"),
    HELP_CIRCLE("mdih-help-circle", "F02D7"),
    HELP_CIRCLE_OUTLINE("mdih-help-circle-outline", "F0625"),
    HELP_NETWORK("mdih-help-network", "F06F5"),
    HELP_NETWORK_OUTLINE("mdih-help-network-outline", "F0C8A"),
    HELP_RHOMBUS("mdih-help-rhombus", "F0BA5"),
    HELP_RHOMBUS_OUTLINE("mdih-help-rhombus-outline", "F0BA6"),
    HEXADECIMAL("mdih-hexadecimal", "F12A7"),
    HEXAGON("mdih-hexagon", "F02D8"),
    HEXAGON_MULTIPLE("mdih-hexagon-multiple", "F06E1"),
    HEXAGON_MULTIPLE_OUTLINE("mdih-hexagon-multiple-outline", "F10F2"),
    HEXAGON_OUTLINE("mdih-hexagon-outline", "F02D9"),
    HEXAGON_SLICE_1("mdih-hexagon-slice-1", "F0AC3"),
    HEXAGON_SLICE_2("mdih-hexagon-slice-2", "F0AC4"),
    HEXAGON_SLICE_3("mdih-hexagon-slice-3", "F0AC5"),
    HEXAGON_SLICE_4("mdih-hexagon-slice-4", "F0AC6"),
    HEXAGON_SLICE_5("mdih-hexagon-slice-5", "F0AC7"),
    HEXAGON_SLICE_6("mdih-hexagon-slice-6", "F0AC8"),
    HEXAGRAM("mdih-hexagram", "F0AC9"),
    HEXAGRAM_OUTLINE("mdih-hexagram-outline", "F0ACA"),
    HIGH_DEFINITION("mdih-high-definition", "F07CF"),
    HIGH_DEFINITION_BOX("mdih-high-definition-box", "F0878"),
    HIGHWAY("mdih-highway", "F05F7"),
    HIKING("mdih-hiking", "F0D7F"),
    HINDUISM("mdih-hinduism", "F0973"),
    HISTORY("mdih-history", "F02DA"),
    HOCKEY_PUCK("mdih-hockey-puck", "F0879"),
    HOCKEY_STICKS("mdih-hockey-sticks", "F087A"),
    HOLOLENS("mdih-hololens", "F02DB"),
    HOME("mdih-home", "F02DC"),
    HOME_ACCOUNT("mdih-home-account", "F0826"),
    HOME_ALERT("mdih-home-alert", "F087B"),
    HOME_ALERT_OUTLINE("mdih-home-alert-outline", "F15D0"),
    HOME_ANALYTICS("mdih-home-analytics", "F0EBA"),
    HOME_ASSISTANT("mdih-home-assistant", "F07D0"),
    HOME_AUTOMATION("mdih-home-automation", "F07D1"),
    HOME_CIRCLE("mdih-home-circle", "F07D2"),
    HOME_CIRCLE_OUTLINE("mdih-home-circle-outline", "F104D"),
    HOME_CITY("mdih-home-city", "F0D15"),
    HOME_CITY_OUTLINE("mdih-home-city-outline", "F0D16"),
    HOME_CURRENCY_USD("mdih-home-currency-usd", "F08AF"),
    HOME_EDIT("mdih-home-edit", "F1159"),
    HOME_EDIT_OUTLINE("mdih-home-edit-outline", "F115A"),
    HOME_EXPORT_OUTLINE("mdih-home-export-outline", "F0F9B"),
    HOME_FLOOD("mdih-home-flood", "F0EFA"),
    HOME_FLOOR_0("mdih-home-floor-0", "F0DD2"),
    HOME_FLOOR_1("mdih-home-floor-1", "F0D80"),
    HOME_FLOOR_2("mdih-home-floor-2", "F0D81"),
    HOME_FLOOR_3("mdih-home-floor-3", "F0D82"),
    HOME_FLOOR_A("mdih-home-floor-a", "F0D83"),
    HOME_FLOOR_B("mdih-home-floor-b", "F0D84"),
    HOME_FLOOR_G("mdih-home-floor-g", "F0D85"),
    HOME_FLOOR_L("mdih-home-floor-l", "F0D86"),
    HOME_FLOOR_NEGATIVE_1("mdih-home-floor-negative-1", "F0DD3"),
    HOME_GROUP("mdih-home-group", "F0DD4"),
    HOME_HEART("mdih-home-heart", "F0827"),
    HOME_IMPORT_OUTLINE("mdih-home-import-outline", "F0F9C"),
    HOME_LIGHTBULB("mdih-home-lightbulb", "F1251"),
    HOME_LIGHTBULB_OUTLINE("mdih-home-lightbulb-outline", "F1252"),
    HOME_LOCK("mdih-home-lock", "F08EB"),
    HOME_LOCK_OPEN("mdih-home-lock-open", "F08EC"),
    HOME_MAP_MARKER("mdih-home-map-marker", "F05F8"),
    HOME_MINUS("mdih-home-minus", "F0974"),
    HOME_MINUS_OUTLINE("mdih-home-minus-outline", "F13D5"),
    HOME_MODERN("mdih-home-modern", "F02DD"),
    HOME_OUTLINE("mdih-home-outline", "F06A1"),
    HOME_PLUS("mdih-home-plus", "F0975"),
    HOME_PLUS_OUTLINE("mdih-home-plus-outline", "F13D6"),
    HOME_REMOVE("mdih-home-remove", "F1247"),
    HOME_REMOVE_OUTLINE("mdih-home-remove-outline", "F13D7"),
    HOME_ROOF("mdih-home-roof", "F112B"),
    HOME_SEARCH("mdih-home-search", "F13B0"),
    HOME_SEARCH_OUTLINE("mdih-home-search-outline", "F13B1"),
    HOME_THERMOMETER("mdih-home-thermometer", "F0F54"),
    HOME_THERMOMETER_OUTLINE("mdih-home-thermometer-outline", "F0F55"),
    HOME_VARIANT("mdih-home-variant", "F02DE"),
    HOME_VARIANT_OUTLINE("mdih-home-variant-outline", "F0BA7"),
    HOOK("mdih-hook", "F06E2"),
    HOOK_OFF("mdih-hook-off", "F06E3"),
    HOPS("mdih-hops", "F02DF"),
    HORIZONTAL_ROTATE_CLOCKWISE("mdih-horizontal-rotate-clockwise", "F10F3"),
    HORIZONTAL_ROTATE_COUNTERCLOCKWISE("mdih-horizontal-rotate-counterclockwise", "F10F4"),
    HORSE("mdih-horse", "F15BF"),
    HORSE_HUMAN("mdih-horse-human", "F15C0"),
    HORSE_VARIANT("mdih-horse-variant", "F15C1"),
    HORSESHOE("mdih-horseshoe", "F0A58"),
    HOSPITAL("mdih-hospital", "F0FF6"),
    HOSPITAL_BOX("mdih-hospital-box", "F02E0"),
    HOSPITAL_BOX_OUTLINE("mdih-hospital-box-outline", "F0FF7"),
    HOSPITAL_BUILDING("mdih-hospital-building", "F02E1"),
    HOSPITAL_MARKER("mdih-hospital-marker", "F02E2"),
    HOT_TUB("mdih-hot-tub", "F0828"),
    HOURS_24("mdih-hours-24", "F1478"),
    HUBSPOT("mdih-hubspot", "F0D17"),
    HULU("mdih-hulu", "F0829"),
    HUMAN("mdih-human", "F02E6"),
    HUMAN_BABY_CHANGING_TABLE("mdih-human-baby-changing-table", "F138B"),
    HUMAN_CANE("mdih-human-cane", "F1581"),
    HUMAN_CAPACITY_DECREASE("mdih-human-capacity-decrease", "F159B"),
    HUMAN_CAPACITY_INCREASE("mdih-human-capacity-increase", "F159C"),
    HUMAN_CHILD("mdih-human-child", "F02E7"),
    HUMAN_EDIT("mdih-human-edit", "F14E8"),
    HUMAN_FEMALE("mdih-human-female", "F0649"),
    HUMAN_FEMALE_BOY("mdih-human-female-boy", "F0A59"),
    HUMAN_FEMALE_DANCE("mdih-human-female-dance", "F15C9"),
    HUMAN_FEMALE_FEMALE("mdih-human-female-female", "F0A5A"),
    HUMAN_FEMALE_GIRL("mdih-human-female-girl", "F0A5B"),
    HUMAN_GREETING("mdih-human-greeting", "F064A"),
    HUMAN_GREETING_PROXIMITY("mdih-human-greeting-proximity", "F159D"),
    HUMAN_HANDSDOWN("mdih-human-handsdown", "F064B"),
    HUMAN_HANDSUP("mdih-human-handsup", "F064C"),
    HUMAN_MALE("mdih-human-male", "F064D"),
    HUMAN_MALE_BOY("mdih-human-male-boy", "F0A5C"),
    HUMAN_MALE_CHILD("mdih-human-male-child", "F138C"),
    HUMAN_MALE_FEMALE("mdih-human-male-female", "F02E8"),
    HUMAN_MALE_GIRL("mdih-human-male-girl", "F0A5D"),
    HUMAN_MALE_HEIGHT("mdih-human-male-height", "F0EFB"),
    HUMAN_MALE_HEIGHT_VARIANT("mdih-human-male-height-variant", "F0EFC"),
    HUMAN_MALE_MALE("mdih-human-male-male", "F0A5E"),
    HUMAN_PREGNANT("mdih-human-pregnant", "F05CF"),
    HUMAN_QUEUE("mdih-human-queue", "F1571"),
    HUMAN_SCOOTER("mdih-human-scooter", "F11E9"),
    HUMAN_WHEELCHAIR("mdih-human-wheelchair", "F138D"),
    HUMBLE_BUNDLE("mdih-humble-bundle", "F0744"),
    HVAC("mdih-hvac", "F1352"),
    HVAC_OFF("mdih-hvac-off", "F159E"),
    HYDRAULIC_OIL_LEVEL("mdih-hydraulic-oil-level", "F1324"),
    HYDRAULIC_OIL_TEMPERATURE("mdih-hydraulic-oil-temperature", "F1325"),
    HYDRO_POWER("mdih-hydro-power", "F12E5");

    public static MaterialDesignH findByDescription(String description) {
        for (MaterialDesignH font : values()) {
            if (font.getDescription().equals(description)) {
                return font;
            }
        }
        throw new IllegalArgumentException("Icon description '" + description + "' is invalid!");
    }

    private String description;
    private int code;

    MaterialDesignH(String description, String code) {
        this.description = description;
        this.code = Integer.parseInt(code, 16);
    }

    @Override
    public String getDescription() {
        return description;
    }

    @Override
    public int getCode() {
        return code;
    }
}
