/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2015-2020 Andres Almiray
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kordamp.ikonli.materialdesign;

import org.kordamp.ikonli.Ikon;

/**
 * @author Andres Almiray
 */
public enum MaterialDesignP implements Ikon {
    PAC_MAN("mdip-pac-man", "F0BAF"),
    PACKAGE("mdip-package", "F03D3"),
    PACKAGE_DOWN("mdip-package-down", "F03D4"),
    PACKAGE_UP("mdip-package-up", "F03D5"),
    PACKAGE_VARIANT("mdip-package-variant", "F03D6"),
    PACKAGE_VARIANT_CLOSED("mdip-package-variant-closed", "F03D7"),
    PAGE_FIRST("mdip-page-first", "F0600"),
    PAGE_LAST("mdip-page-last", "F0601"),
    PAGE_LAYOUT_BODY("mdip-page-layout-body", "F06FA"),
    PAGE_LAYOUT_FOOTER("mdip-page-layout-footer", "F06FB"),
    PAGE_LAYOUT_HEADER("mdip-page-layout-header", "F06FC"),
    PAGE_LAYOUT_HEADER_FOOTER("mdip-page-layout-header-footer", "F0F7F"),
    PAGE_LAYOUT_SIDEBAR_LEFT("mdip-page-layout-sidebar-left", "F06FD"),
    PAGE_LAYOUT_SIDEBAR_RIGHT("mdip-page-layout-sidebar-right", "F06FE"),
    PAGE_NEXT("mdip-page-next", "F0BB0"),
    PAGE_NEXT_OUTLINE("mdip-page-next-outline", "F0BB1"),
    PAGE_PREVIOUS("mdip-page-previous", "F0BB2"),
    PAGE_PREVIOUS_OUTLINE("mdip-page-previous-outline", "F0BB3"),
    PAIL("mdip-pail", "F1417"),
    PAIL_MINUS("mdip-pail-minus", "F1437"),
    PAIL_MINUS_OUTLINE("mdip-pail-minus-outline", "F143C"),
    PAIL_OFF("mdip-pail-off", "F1439"),
    PAIL_OFF_OUTLINE("mdip-pail-off-outline", "F143E"),
    PAIL_OUTLINE("mdip-pail-outline", "F143A"),
    PAIL_PLUS("mdip-pail-plus", "F1436"),
    PAIL_PLUS_OUTLINE("mdip-pail-plus-outline", "F143B"),
    PAIL_REMOVE("mdip-pail-remove", "F1438"),
    PAIL_REMOVE_OUTLINE("mdip-pail-remove-outline", "F143D"),
    PALETTE("mdip-palette", "F03D8"),
    PALETTE_ADVANCED("mdip-palette-advanced", "F03D9"),
    PALETTE_OUTLINE("mdip-palette-outline", "F0E0C"),
    PALETTE_SWATCH("mdip-palette-swatch", "F08B5"),
    PALETTE_SWATCH_OUTLINE("mdip-palette-swatch-outline", "F135C"),
    PALM_TREE("mdip-palm-tree", "F1055"),
    PAN("mdip-pan", "F0BB4"),
    PAN_BOTTOM_LEFT("mdip-pan-bottom-left", "F0BB5"),
    PAN_BOTTOM_RIGHT("mdip-pan-bottom-right", "F0BB6"),
    PAN_DOWN("mdip-pan-down", "F0BB7"),
    PAN_HORIZONTAL("mdip-pan-horizontal", "F0BB8"),
    PAN_LEFT("mdip-pan-left", "F0BB9"),
    PAN_RIGHT("mdip-pan-right", "F0BBA"),
    PAN_TOP_LEFT("mdip-pan-top-left", "F0BBB"),
    PAN_TOP_RIGHT("mdip-pan-top-right", "F0BBC"),
    PAN_UP("mdip-pan-up", "F0BBD"),
    PAN_VERTICAL("mdip-pan-vertical", "F0BBE"),
    PANDA("mdip-panda", "F03DA"),
    PANDORA("mdip-pandora", "F03DB"),
    PANORAMA("mdip-panorama", "F03DC"),
    PANORAMA_FISHEYE("mdip-panorama-fisheye", "F03DD"),
    PANORAMA_HORIZONTAL("mdip-panorama-horizontal", "F03DE"),
    PANORAMA_VERTICAL("mdip-panorama-vertical", "F03DF"),
    PANORAMA_WIDE_ANGLE("mdip-panorama-wide-angle", "F03E0"),
    PAPER_CUT_VERTICAL("mdip-paper-cut-vertical", "F03E1"),
    PAPER_ROLL("mdip-paper-roll", "F1157"),
    PAPER_ROLL_OUTLINE("mdip-paper-roll-outline", "F1158"),
    PAPERCLIP("mdip-paperclip", "F03E2"),
    PARACHUTE("mdip-parachute", "F0CB4"),
    PARACHUTE_OUTLINE("mdip-parachute-outline", "F0CB5"),
    PARKING("mdip-parking", "F03E3"),
    PARTY_POPPER("mdip-party-popper", "F1056"),
    PASSPORT("mdip-passport", "F07E3"),
    PASSPORT_BIOMETRIC("mdip-passport-biometric", "F0DE1"),
    PASTA("mdip-pasta", "F1160"),
    PATIO_HEATER("mdip-patio-heater", "F0F80"),
    PATREON("mdip-patreon", "F0882"),
    PAUSE("mdip-pause", "F03E4"),
    PAUSE_CIRCLE("mdip-pause-circle", "F03E5"),
    PAUSE_CIRCLE_OUTLINE("mdip-pause-circle-outline", "F03E6"),
    PAUSE_OCTAGON("mdip-pause-octagon", "F03E7"),
    PAUSE_OCTAGON_OUTLINE("mdip-pause-octagon-outline", "F03E8"),
    PAW("mdip-paw", "F03E9"),
    PAW_OFF("mdip-paw-off", "F0657"),
    PAW_OFF_OUTLINE("mdip-paw-off-outline", "F1676"),
    PAW_OUTLINE("mdip-paw-outline", "F1675"),
    PDF_BOX("mdip-pdf-box", "F0E56"),
    PEACE("mdip-peace", "F0884"),
    PEANUT("mdip-peanut", "F0FFC"),
    PEANUT_OFF("mdip-peanut-off", "F0FFD"),
    PEANUT_OFF_OUTLINE("mdip-peanut-off-outline", "F0FFF"),
    PEANUT_OUTLINE("mdip-peanut-outline", "F0FFE"),
    PEN("mdip-pen", "F03EA"),
    PEN_LOCK("mdip-pen-lock", "F0DE2"),
    PEN_MINUS("mdip-pen-minus", "F0DE3"),
    PEN_OFF("mdip-pen-off", "F0DE4"),
    PEN_PLUS("mdip-pen-plus", "F0DE5"),
    PEN_REMOVE("mdip-pen-remove", "F0DE6"),
    PENCIL("mdip-pencil", "F03EB"),
    PENCIL_BOX("mdip-pencil-box", "F03EC"),
    PENCIL_BOX_MULTIPLE("mdip-pencil-box-multiple", "F1144"),
    PENCIL_BOX_MULTIPLE_OUTLINE("mdip-pencil-box-multiple-outline", "F1145"),
    PENCIL_BOX_OUTLINE("mdip-pencil-box-outline", "F03ED"),
    PENCIL_CIRCLE("mdip-pencil-circle", "F06FF"),
    PENCIL_CIRCLE_OUTLINE("mdip-pencil-circle-outline", "F0776"),
    PENCIL_LOCK("mdip-pencil-lock", "F03EE"),
    PENCIL_LOCK_OUTLINE("mdip-pencil-lock-outline", "F0DE7"),
    PENCIL_MINUS("mdip-pencil-minus", "F0DE8"),
    PENCIL_MINUS_OUTLINE("mdip-pencil-minus-outline", "F0DE9"),
    PENCIL_OFF("mdip-pencil-off", "F03EF"),
    PENCIL_OFF_OUTLINE("mdip-pencil-off-outline", "F0DEA"),
    PENCIL_OUTLINE("mdip-pencil-outline", "F0CB6"),
    PENCIL_PLUS("mdip-pencil-plus", "F0DEB"),
    PENCIL_PLUS_OUTLINE("mdip-pencil-plus-outline", "F0DEC"),
    PENCIL_REMOVE("mdip-pencil-remove", "F0DED"),
    PENCIL_REMOVE_OUTLINE("mdip-pencil-remove-outline", "F0DEE"),
    PENCIL_RULER("mdip-pencil-ruler", "F1353"),
    PENGUIN("mdip-penguin", "F0EC0"),
    PENTAGON("mdip-pentagon", "F0701"),
    PENTAGON_OUTLINE("mdip-pentagon-outline", "F0700"),
    PENTAGRAM("mdip-pentagram", "F1667"),
    PERCENT("mdip-percent", "F03F0"),
    PERCENT_OUTLINE("mdip-percent-outline", "F1278"),
    PERIODIC_TABLE("mdip-periodic-table", "F08B6"),
    PERSPECTIVE_LESS("mdip-perspective-less", "F0D23"),
    PERSPECTIVE_MORE("mdip-perspective-more", "F0D24"),
    PHARMACY("mdip-pharmacy", "F03F1"),
    PHONE("mdip-phone", "F03F2"),
    PHONE_ALERT("mdip-phone-alert", "F0F1A"),
    PHONE_ALERT_OUTLINE("mdip-phone-alert-outline", "F118E"),
    PHONE_BLUETOOTH("mdip-phone-bluetooth", "F03F3"),
    PHONE_BLUETOOTH_OUTLINE("mdip-phone-bluetooth-outline", "F118F"),
    PHONE_CANCEL("mdip-phone-cancel", "F10BC"),
    PHONE_CANCEL_OUTLINE("mdip-phone-cancel-outline", "F1190"),
    PHONE_CHECK("mdip-phone-check", "F11A9"),
    PHONE_CHECK_OUTLINE("mdip-phone-check-outline", "F11AA"),
    PHONE_CLASSIC("mdip-phone-classic", "F0602"),
    PHONE_CLASSIC_OFF("mdip-phone-classic-off", "F1279"),
    PHONE_DIAL("mdip-phone-dial", "F1559"),
    PHONE_DIAL_OUTLINE("mdip-phone-dial-outline", "F155A"),
    PHONE_FORWARD("mdip-phone-forward", "F03F4"),
    PHONE_FORWARD_OUTLINE("mdip-phone-forward-outline", "F1191"),
    PHONE_HANGUP("mdip-phone-hangup", "F03F5"),
    PHONE_HANGUP_OUTLINE("mdip-phone-hangup-outline", "F1192"),
    PHONE_IN_TALK("mdip-phone-in-talk", "F03F6"),
    PHONE_IN_TALK_OUTLINE("mdip-phone-in-talk-outline", "F1182"),
    PHONE_INCOMING("mdip-phone-incoming", "F03F7"),
    PHONE_INCOMING_OUTLINE("mdip-phone-incoming-outline", "F1193"),
    PHONE_LOCK("mdip-phone-lock", "F03F8"),
    PHONE_LOCK_OUTLINE("mdip-phone-lock-outline", "F1194"),
    PHONE_LOG("mdip-phone-log", "F03F9"),
    PHONE_LOG_OUTLINE("mdip-phone-log-outline", "F1195"),
    PHONE_MESSAGE("mdip-phone-message", "F1196"),
    PHONE_MESSAGE_OUTLINE("mdip-phone-message-outline", "F1197"),
    PHONE_MINUS("mdip-phone-minus", "F0658"),
    PHONE_MINUS_OUTLINE("mdip-phone-minus-outline", "F1198"),
    PHONE_MISSED("mdip-phone-missed", "F03FA"),
    PHONE_MISSED_OUTLINE("mdip-phone-missed-outline", "F11A5"),
    PHONE_OFF("mdip-phone-off", "F0DEF"),
    PHONE_OFF_OUTLINE("mdip-phone-off-outline", "F11A6"),
    PHONE_OUTGOING("mdip-phone-outgoing", "F03FB"),
    PHONE_OUTGOING_OUTLINE("mdip-phone-outgoing-outline", "F1199"),
    PHONE_OUTLINE("mdip-phone-outline", "F0DF0"),
    PHONE_PAUSED("mdip-phone-paused", "F03FC"),
    PHONE_PAUSED_OUTLINE("mdip-phone-paused-outline", "F119A"),
    PHONE_PLUS("mdip-phone-plus", "F0659"),
    PHONE_PLUS_OUTLINE("mdip-phone-plus-outline", "F119B"),
    PHONE_REMOVE("mdip-phone-remove", "F152F"),
    PHONE_REMOVE_OUTLINE("mdip-phone-remove-outline", "F1530"),
    PHONE_RETURN("mdip-phone-return", "F082F"),
    PHONE_RETURN_OUTLINE("mdip-phone-return-outline", "F119C"),
    PHONE_RING("mdip-phone-ring", "F11AB"),
    PHONE_RING_OUTLINE("mdip-phone-ring-outline", "F11AC"),
    PHONE_ROTATE_LANDSCAPE("mdip-phone-rotate-landscape", "F0885"),
    PHONE_ROTATE_PORTRAIT("mdip-phone-rotate-portrait", "F0886"),
    PHONE_SETTINGS("mdip-phone-settings", "F03FD"),
    PHONE_SETTINGS_OUTLINE("mdip-phone-settings-outline", "F119D"),
    PHONE_VOIP("mdip-phone-voip", "F03FE"),
    PI("mdip-pi", "F03FF"),
    PI_BOX("mdip-pi-box", "F0400"),
    PI_HOLE("mdip-pi-hole", "F0DF1"),
    PIANO("mdip-piano", "F067D"),
    PICKAXE("mdip-pickaxe", "F08B7"),
    PICTURE_IN_PICTURE_BOTTOM_RIGHT("mdip-picture-in-picture-bottom-right", "F0E57"),
    PICTURE_IN_PICTURE_BOTTOM_RIGHT_OUTLINE("mdip-picture-in-picture-bottom-right-outline", "F0E58"),
    PICTURE_IN_PICTURE_TOP_RIGHT("mdip-picture-in-picture-top-right", "F0E59"),
    PICTURE_IN_PICTURE_TOP_RIGHT_OUTLINE("mdip-picture-in-picture-top-right-outline", "F0E5A"),
    PIER("mdip-pier", "F0887"),
    PIER_CRANE("mdip-pier-crane", "F0888"),
    PIG("mdip-pig", "F0401"),
    PIG_VARIANT("mdip-pig-variant", "F1006"),
    PIG_VARIANT_OUTLINE("mdip-pig-variant-outline", "F1678"),
    PIGGY_BANK("mdip-piggy-bank", "F1007"),
    PIGGY_BANK_OUTLINE("mdip-piggy-bank-outline", "F1679"),
    PILL("mdip-pill", "F0402"),
    PILLAR("mdip-pillar", "F0702"),
    PIN("mdip-pin", "F0403"),
    PIN_OFF("mdip-pin-off", "F0404"),
    PIN_OFF_OUTLINE("mdip-pin-off-outline", "F0930"),
    PIN_OUTLINE("mdip-pin-outline", "F0931"),
    PINE_TREE("mdip-pine-tree", "F0405"),
    PINE_TREE_BOX("mdip-pine-tree-box", "F0406"),
    PINE_TREE_FIRE("mdip-pine-tree-fire", "F141A"),
    PINTEREST("mdip-pinterest", "F0407"),
    PINWHEEL("mdip-pinwheel", "F0AD5"),
    PINWHEEL_OUTLINE("mdip-pinwheel-outline", "F0AD6"),
    PIPE("mdip-pipe", "F07E5"),
    PIPE_DISCONNECTED("mdip-pipe-disconnected", "F07E6"),
    PIPE_LEAK("mdip-pipe-leak", "F0889"),
    PIPE_WRENCH("mdip-pipe-wrench", "F1354"),
    PIRATE("mdip-pirate", "F0A08"),
    PISTOL("mdip-pistol", "F0703"),
    PISTON("mdip-piston", "F088A"),
    PITCHFORK("mdip-pitchfork", "F1553"),
    PIZZA("mdip-pizza", "F0409"),
    PLAY("mdip-play", "F040A"),
    PLAY_BOX("mdip-play-box", "F127A"),
    PLAY_BOX_MULTIPLE("mdip-play-box-multiple", "F0D19"),
    PLAY_BOX_MULTIPLE_OUTLINE("mdip-play-box-multiple-outline", "F13E6"),
    PLAY_BOX_OUTLINE("mdip-play-box-outline", "F040B"),
    PLAY_CIRCLE("mdip-play-circle", "F040C"),
    PLAY_CIRCLE_OUTLINE("mdip-play-circle-outline", "F040D"),
    PLAY_NETWORK("mdip-play-network", "F088B"),
    PLAY_NETWORK_OUTLINE("mdip-play-network-outline", "F0CB7"),
    PLAY_OUTLINE("mdip-play-outline", "F0F1B"),
    PLAY_PAUSE("mdip-play-pause", "F040E"),
    PLAY_PROTECTED_CONTENT("mdip-play-protected-content", "F040F"),
    PLAY_SPEED("mdip-play-speed", "F08FF"),
    PLAYLIST_CHECK("mdip-playlist-check", "F05C7"),
    PLAYLIST_EDIT("mdip-playlist-edit", "F0900"),
    PLAYLIST_MINUS("mdip-playlist-minus", "F0410"),
    PLAYLIST_MUSIC("mdip-playlist-music", "F0CB8"),
    PLAYLIST_MUSIC_OUTLINE("mdip-playlist-music-outline", "F0CB9"),
    PLAYLIST_PLAY("mdip-playlist-play", "F0411"),
    PLAYLIST_PLUS("mdip-playlist-plus", "F0412"),
    PLAYLIST_REMOVE("mdip-playlist-remove", "F0413"),
    PLAYLIST_STAR("mdip-playlist-star", "F0DF2"),
    PLEX("mdip-plex", "F06BA"),
    PLUS("mdip-plus", "F0415"),
    PLUS_BOX("mdip-plus-box", "F0416"),
    PLUS_BOX_MULTIPLE("mdip-plus-box-multiple", "F0334"),
    PLUS_BOX_MULTIPLE_OUTLINE("mdip-plus-box-multiple-outline", "F1143"),
    PLUS_BOX_OUTLINE("mdip-plus-box-outline", "F0704"),
    PLUS_CIRCLE("mdip-plus-circle", "F0417"),
    PLUS_CIRCLE_MULTIPLE("mdip-plus-circle-multiple", "F034C"),
    PLUS_CIRCLE_MULTIPLE_OUTLINE("mdip-plus-circle-multiple-outline", "F0418"),
    PLUS_CIRCLE_OUTLINE("mdip-plus-circle-outline", "F0419"),
    PLUS_MINUS("mdip-plus-minus", "F0992"),
    PLUS_MINUS_BOX("mdip-plus-minus-box", "F0993"),
    PLUS_MINUS_VARIANT("mdip-plus-minus-variant", "F14C9"),
    PLUS_NETWORK("mdip-plus-network", "F041A"),
    PLUS_NETWORK_OUTLINE("mdip-plus-network-outline", "F0CBA"),
    PLUS_ONE("mdip-plus-one", "F041B"),
    PLUS_OUTLINE("mdip-plus-outline", "F0705"),
    PLUS_THICK("mdip-plus-thick", "F11EC"),
    PODCAST("mdip-podcast", "F0994"),
    PODIUM("mdip-podium", "F0D25"),
    PODIUM_BRONZE("mdip-podium-bronze", "F0D26"),
    PODIUM_GOLD("mdip-podium-gold", "F0D27"),
    PODIUM_SILVER("mdip-podium-silver", "F0D28"),
    POINT_OF_SALE("mdip-point-of-sale", "F0D92"),
    POKEBALL("mdip-pokeball", "F041D"),
    POKEMON_GO("mdip-pokemon-go", "F0A09"),
    POKER_CHIP("mdip-poker-chip", "F0830"),
    POLAROID("mdip-polaroid", "F041E"),
    POLICE_BADGE("mdip-police-badge", "F1167"),
    POLICE_BADGE_OUTLINE("mdip-police-badge-outline", "F1168"),
    POLL("mdip-poll", "F041F"),
    POLL_BOX("mdip-poll-box", "F0420"),
    POLL_BOX_OUTLINE("mdip-poll-box-outline", "F127B"),
    POLO("mdip-polo", "F14C3"),
    POLYMER("mdip-polymer", "F0421"),
    POOL("mdip-pool", "F0606"),
    POPCORN("mdip-popcorn", "F0422"),
    POST("mdip-post", "F1008"),
    POST_OUTLINE("mdip-post-outline", "F1009"),
    POSTAGE_STAMP("mdip-postage-stamp", "F0CBB"),
    POT("mdip-pot", "F02E5"),
    POT_MIX("mdip-pot-mix", "F065B"),
    POT_MIX_OUTLINE("mdip-pot-mix-outline", "F0677"),
    POT_OUTLINE("mdip-pot-outline", "F02FF"),
    POT_STEAM("mdip-pot-steam", "F065A"),
    POT_STEAM_OUTLINE("mdip-pot-steam-outline", "F0326"),
    POUND("mdip-pound", "F0423"),
    POUND_BOX("mdip-pound-box", "F0424"),
    POUND_BOX_OUTLINE("mdip-pound-box-outline", "F117F"),
    POWER("mdip-power", "F0425"),
    POWER_CYCLE("mdip-power-cycle", "F0901"),
    POWER_OFF("mdip-power-off", "F0902"),
    POWER_ON("mdip-power-on", "F0903"),
    POWER_PLUG("mdip-power-plug", "F06A5"),
    POWER_PLUG_OFF("mdip-power-plug-off", "F06A6"),
    POWER_PLUG_OFF_OUTLINE("mdip-power-plug-off-outline", "F1424"),
    POWER_PLUG_OUTLINE("mdip-power-plug-outline", "F1425"),
    POWER_SETTINGS("mdip-power-settings", "F0426"),
    POWER_SLEEP("mdip-power-sleep", "F0904"),
    POWER_SOCKET("mdip-power-socket", "F0427"),
    POWER_SOCKET_AU("mdip-power-socket-au", "F0905"),
    POWER_SOCKET_DE("mdip-power-socket-de", "F1107"),
    POWER_SOCKET_EU("mdip-power-socket-eu", "F07E7"),
    POWER_SOCKET_FR("mdip-power-socket-fr", "F1108"),
    POWER_SOCKET_IT("mdip-power-socket-it", "F14FF"),
    POWER_SOCKET_JP("mdip-power-socket-jp", "F1109"),
    POWER_SOCKET_UK("mdip-power-socket-uk", "F07E8"),
    POWER_SOCKET_US("mdip-power-socket-us", "F07E9"),
    POWER_STANDBY("mdip-power-standby", "F0906"),
    POWERSHELL("mdip-powershell", "F0A0A"),
    PRESCRIPTION("mdip-prescription", "F0706"),
    PRESENTATION("mdip-presentation", "F0428"),
    PRESENTATION_PLAY("mdip-presentation-play", "F0429"),
    PRETZEL("mdip-pretzel", "F1562"),
    PRINTER("mdip-printer", "F042A"),
    PRINTER_3D("mdip-printer-3d", "F042B"),
    PRINTER_3D_NOZZLE("mdip-printer-3d-nozzle", "F0E5B"),
    PRINTER_3D_NOZZLE_ALERT("mdip-printer-3d-nozzle-alert", "F11C0"),
    PRINTER_3D_NOZZLE_ALERT_OUTLINE("mdip-printer-3d-nozzle-alert-outline", "F11C1"),
    PRINTER_3D_NOZZLE_OUTLINE("mdip-printer-3d-nozzle-outline", "F0E5C"),
    PRINTER_ALERT("mdip-printer-alert", "F042C"),
    PRINTER_CHECK("mdip-printer-check", "F1146"),
    PRINTER_EYE("mdip-printer-eye", "F1458"),
    PRINTER_OFF("mdip-printer-off", "F0E5D"),
    PRINTER_POS("mdip-printer-pos", "F1057"),
    PRINTER_SEARCH("mdip-printer-search", "F1457"),
    PRINTER_SETTINGS("mdip-printer-settings", "F0707"),
    PRINTER_WIRELESS("mdip-printer-wireless", "F0A0B"),
    PRIORITY_HIGH("mdip-priority-high", "F0603"),
    PRIORITY_LOW("mdip-priority-low", "F0604"),
    PROFESSIONAL_HEXAGON("mdip-professional-hexagon", "F042D"),
    PROGRESS_ALERT("mdip-progress-alert", "F0CBC"),
    PROGRESS_CHECK("mdip-progress-check", "F0995"),
    PROGRESS_CLOCK("mdip-progress-clock", "F0996"),
    PROGRESS_CLOSE("mdip-progress-close", "F110A"),
    PROGRESS_DOWNLOAD("mdip-progress-download", "F0997"),
    PROGRESS_QUESTION("mdip-progress-question", "F1522"),
    PROGRESS_UPLOAD("mdip-progress-upload", "F0998"),
    PROGRESS_WRENCH("mdip-progress-wrench", "F0CBD"),
    PROJECTOR("mdip-projector", "F042E"),
    PROJECTOR_SCREEN("mdip-projector-screen", "F042F"),
    PROPANE_TANK("mdip-propane-tank", "F1357"),
    PROPANE_TANK_OUTLINE("mdip-propane-tank-outline", "F1358"),
    PROTOCOL("mdip-protocol", "F0FD8"),
    PUBLISH("mdip-publish", "F06A7"),
    PULSE("mdip-pulse", "F0430"),
    PUMP("mdip-pump", "F1402"),
    PUMPKIN("mdip-pumpkin", "F0BBF"),
    PURSE("mdip-purse", "F0F1C"),
    PURSE_OUTLINE("mdip-purse-outline", "F0F1D"),
    PUZZLE("mdip-puzzle", "F0431"),
    PUZZLE_CHECK("mdip-puzzle-check", "F1426"),
    PUZZLE_CHECK_OUTLINE("mdip-puzzle-check-outline", "F1427"),
    PUZZLE_EDIT("mdip-puzzle-edit", "F14D3"),
    PUZZLE_EDIT_OUTLINE("mdip-puzzle-edit-outline", "F14D9"),
    PUZZLE_HEART("mdip-puzzle-heart", "F14D4"),
    PUZZLE_HEART_OUTLINE("mdip-puzzle-heart-outline", "F14DA"),
    PUZZLE_MINUS("mdip-puzzle-minus", "F14D1"),
    PUZZLE_MINUS_OUTLINE("mdip-puzzle-minus-outline", "F14D7"),
    PUZZLE_OUTLINE("mdip-puzzle-outline", "F0A66"),
    PUZZLE_PLUS("mdip-puzzle-plus", "F14D0"),
    PUZZLE_PLUS_OUTLINE("mdip-puzzle-plus-outline", "F14D6"),
    PUZZLE_REMOVE("mdip-puzzle-remove", "F14D2"),
    PUZZLE_REMOVE_OUTLINE("mdip-puzzle-remove-outline", "F14D8"),
    PUZZLE_STAR("mdip-puzzle-star", "F14D5"),
    PUZZLE_STAR_OUTLINE("mdip-puzzle-star-outline", "F14DB");

    public static MaterialDesignP findByDescription(String description) {
        for (MaterialDesignP font : values()) {
            if (font.getDescription().equals(description)) {
                return font;
            }
        }
        throw new IllegalArgumentException("Icon description '" + description + "' is invalid!");
    }

    private String description;
    private int code;

    MaterialDesignP(String description, String code) {
        this.description = description;
        this.code = Integer.parseInt(code, 16);
    }

    @Override
    public String getDescription() {
        return description;
    }

    @Override
    public int getCode() {
        return code;
    }
}
